
asm.bin:     file format binary


Disassembly of section .data:

0000000000000000 <.data>:
   0:	66 90                	xchg   ax,ax
   2:	66 90                	xchg   ax,ax
   4:	66 90                	xchg   ax,ax
   6:	66 90                	xchg   ax,ax
   8:	66 90                	xchg   ax,ax
   a:	66 90                	xchg   ax,ax
   c:	66 90                	xchg   ax,ax
   e:	66 90                	xchg   ax,ax
  10:	53                   	push   rbx
  11:	55                   	push   rbp
  12:	56                   	push   rsi
  13:	57                   	push   rdi
  14:	41 50                	push   r8
  16:	41 51                	push   r9
  18:	48 81 ec a4 6a 00 00 	sub    rsp,0x6aa4
  1f:	45 31 c0             	xor    r8d,r8d
  22:	4c 8d 0c 24          	lea    r9,[rsp]
  26:	48 b9 01 00 00 00 00 	movabs rcx,0x1
  2d:	00 00 00 
  30:	48 ba 02 00 00 00 00 	movabs rdx,0x2
  37:	00 00 00 
  3a:	48 b8 00 20 00 00 00 	movabs rax,0x2000
  41:	00 00 00 
  44:	48 83 eb 00          	sub    rbx,0x0
  48:	48 83 ed 00          	sub    rbp,0x0
  4c:	48 83 ee 00          	sub    rsi,0x0
  50:	48 83 ef 00          	sub    rdi,0x0
  54:	49 83 e8 00          	sub    r8,0x0
  58:	49 83 e9 00          	sub    r9,0x0
  5c:	49 83 ea 00          	sub    r10,0x0
  60:	49 83 eb 00          	sub    r11,0x0
  64:	49 83 ec 00          	sub    r12,0x0
  68:	49 83 ed 00          	sub    r13,0x0
  6c:	49 83 ee 00          	sub    r14,0x0
  70:	49 83 ef 00          	sub    r15,0x0
  74:	90                   	nop
  75:	90                   	nop
  76:	90                   	nop
  77:	90                   	nop
  78:	90                   	nop
  79:	90                   	nop
  7a:	90                   	nop
  7b:	90                   	nop
  7c:	90                   	nop
  7d:	90                   	nop
  7e:	90                   	nop
  7f:	90                   	nop
  80:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
  83:	ff c3                	inc    ebx
  85:	ff c5                	inc    ebp
  87:	ff c6                	inc    esi
  89:	ff c7                	inc    edi
  8b:	ff c3                	inc    ebx
  8d:	ff c5                	inc    ebp
  8f:	ff c6                	inc    esi
  91:	ff c7                	inc    edi
  93:	ff c3                	inc    ebx
  95:	ff c5                	inc    ebp
  97:	ff c6                	inc    esi
  99:	ff c7                	inc    edi
  9b:	ff c3                	inc    ebx
  9d:	ff c5                	inc    ebp
  9f:	ff c6                	inc    esi
  a1:	ff c7                	inc    edi
  a3:	ff c3                	inc    ebx
  a5:	ff c5                	inc    ebp
  a7:	ff c6                	inc    esi
  a9:	ff c7                	inc    edi
  ab:	ff c3                	inc    ebx
  ad:	ff c5                	inc    ebp
  af:	ff c6                	inc    esi
  b1:	ff c7                	inc    edi
  b3:	ff c3                	inc    ebx
  b5:	ff c5                	inc    ebp
  b7:	ff c6                	inc    esi
  b9:	ff c7                	inc    edi
  bb:	ff c3                	inc    ebx
  bd:	ff c5                	inc    ebp
  bf:	ff c6                	inc    esi
  c1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
  c4:	ff c3                	inc    ebx
  c6:	ff c5                	inc    ebp
  c8:	ff c6                	inc    esi
  ca:	ff c7                	inc    edi
  cc:	ff c3                	inc    ebx
  ce:	ff c5                	inc    ebp
  d0:	ff c6                	inc    esi
  d2:	ff c7                	inc    edi
  d4:	ff c3                	inc    ebx
  d6:	ff c5                	inc    ebp
  d8:	ff c6                	inc    esi
  da:	ff c7                	inc    edi
  dc:	ff c3                	inc    ebx
  de:	ff c5                	inc    ebp
  e0:	ff c6                	inc    esi
  e2:	ff c7                	inc    edi
  e4:	ff c3                	inc    ebx
  e6:	ff c5                	inc    ebp
  e8:	ff c6                	inc    esi
  ea:	ff c7                	inc    edi
  ec:	ff c3                	inc    ebx
  ee:	ff c5                	inc    ebp
  f0:	ff c6                	inc    esi
  f2:	ff c7                	inc    edi
  f4:	ff c3                	inc    ebx
  f6:	ff c5                	inc    ebp
  f8:	ff c6                	inc    esi
  fa:	ff c7                	inc    edi
  fc:	ff c3                	inc    ebx
  fe:	ff c5                	inc    ebp
 100:	ff c6                	inc    esi
 102:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 105:	ff c3                	inc    ebx
 107:	ff c5                	inc    ebp
 109:	ff c6                	inc    esi
 10b:	ff c7                	inc    edi
 10d:	ff c3                	inc    ebx
 10f:	ff c5                	inc    ebp
 111:	ff c6                	inc    esi
 113:	ff c7                	inc    edi
 115:	ff c3                	inc    ebx
 117:	ff c5                	inc    ebp
 119:	ff c6                	inc    esi
 11b:	ff c7                	inc    edi
 11d:	ff c3                	inc    ebx
 11f:	ff c5                	inc    ebp
 121:	ff c6                	inc    esi
 123:	ff c7                	inc    edi
 125:	ff c3                	inc    ebx
 127:	ff c5                	inc    ebp
 129:	ff c6                	inc    esi
 12b:	ff c7                	inc    edi
 12d:	ff c3                	inc    ebx
 12f:	ff c5                	inc    ebp
 131:	ff c6                	inc    esi
 133:	ff c7                	inc    edi
 135:	ff c3                	inc    ebx
 137:	ff c5                	inc    ebp
 139:	ff c6                	inc    esi
 13b:	ff c7                	inc    edi
 13d:	ff c3                	inc    ebx
 13f:	ff c5                	inc    ebp
 141:	ff c6                	inc    esi
 143:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 146:	ff c3                	inc    ebx
 148:	ff c5                	inc    ebp
 14a:	ff c6                	inc    esi
 14c:	ff c7                	inc    edi
 14e:	ff c3                	inc    ebx
 150:	ff c5                	inc    ebp
 152:	ff c6                	inc    esi
 154:	ff c7                	inc    edi
 156:	ff c3                	inc    ebx
 158:	ff c5                	inc    ebp
 15a:	ff c6                	inc    esi
 15c:	ff c7                	inc    edi
 15e:	ff c3                	inc    ebx
 160:	ff c5                	inc    ebp
 162:	ff c6                	inc    esi
 164:	ff c7                	inc    edi
 166:	ff c3                	inc    ebx
 168:	ff c5                	inc    ebp
 16a:	ff c6                	inc    esi
 16c:	ff c7                	inc    edi
 16e:	ff c3                	inc    ebx
 170:	ff c5                	inc    ebp
 172:	ff c6                	inc    esi
 174:	ff c7                	inc    edi
 176:	ff c3                	inc    ebx
 178:	ff c5                	inc    ebp
 17a:	ff c6                	inc    esi
 17c:	ff c7                	inc    edi
 17e:	ff c3                	inc    ebx
 180:	ff c5                	inc    ebp
 182:	ff c6                	inc    esi
 184:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 187:	ff c3                	inc    ebx
 189:	ff c5                	inc    ebp
 18b:	ff c6                	inc    esi
 18d:	ff c7                	inc    edi
 18f:	ff c3                	inc    ebx
 191:	ff c5                	inc    ebp
 193:	ff c6                	inc    esi
 195:	ff c7                	inc    edi
 197:	ff c3                	inc    ebx
 199:	ff c5                	inc    ebp
 19b:	ff c6                	inc    esi
 19d:	ff c7                	inc    edi
 19f:	ff c3                	inc    ebx
 1a1:	ff c5                	inc    ebp
 1a3:	ff c6                	inc    esi
 1a5:	ff c7                	inc    edi
 1a7:	ff c3                	inc    ebx
 1a9:	ff c5                	inc    ebp
 1ab:	ff c6                	inc    esi
 1ad:	ff c7                	inc    edi
 1af:	ff c3                	inc    ebx
 1b1:	ff c5                	inc    ebp
 1b3:	ff c6                	inc    esi
 1b5:	ff c7                	inc    edi
 1b7:	ff c3                	inc    ebx
 1b9:	ff c5                	inc    ebp
 1bb:	ff c6                	inc    esi
 1bd:	ff c7                	inc    edi
 1bf:	ff c3                	inc    ebx
 1c1:	ff c5                	inc    ebp
 1c3:	ff c6                	inc    esi
 1c5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 1c8:	ff c3                	inc    ebx
 1ca:	ff c5                	inc    ebp
 1cc:	ff c6                	inc    esi
 1ce:	ff c7                	inc    edi
 1d0:	ff c3                	inc    ebx
 1d2:	ff c5                	inc    ebp
 1d4:	ff c6                	inc    esi
 1d6:	ff c7                	inc    edi
 1d8:	ff c3                	inc    ebx
 1da:	ff c5                	inc    ebp
 1dc:	ff c6                	inc    esi
 1de:	ff c7                	inc    edi
 1e0:	ff c3                	inc    ebx
 1e2:	ff c5                	inc    ebp
 1e4:	ff c6                	inc    esi
 1e6:	ff c7                	inc    edi
 1e8:	ff c3                	inc    ebx
 1ea:	ff c5                	inc    ebp
 1ec:	ff c6                	inc    esi
 1ee:	ff c7                	inc    edi
 1f0:	ff c3                	inc    ebx
 1f2:	ff c5                	inc    ebp
 1f4:	ff c6                	inc    esi
 1f6:	ff c7                	inc    edi
 1f8:	ff c3                	inc    ebx
 1fa:	ff c5                	inc    ebp
 1fc:	ff c6                	inc    esi
 1fe:	ff c7                	inc    edi
 200:	ff c3                	inc    ebx
 202:	ff c5                	inc    ebp
 204:	ff c6                	inc    esi
 206:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 209:	ff c3                	inc    ebx
 20b:	ff c5                	inc    ebp
 20d:	ff c6                	inc    esi
 20f:	ff c7                	inc    edi
 211:	ff c3                	inc    ebx
 213:	ff c5                	inc    ebp
 215:	ff c6                	inc    esi
 217:	ff c7                	inc    edi
 219:	ff c3                	inc    ebx
 21b:	ff c5                	inc    ebp
 21d:	ff c6                	inc    esi
 21f:	ff c7                	inc    edi
 221:	ff c3                	inc    ebx
 223:	ff c5                	inc    ebp
 225:	ff c6                	inc    esi
 227:	ff c7                	inc    edi
 229:	ff c3                	inc    ebx
 22b:	ff c5                	inc    ebp
 22d:	ff c6                	inc    esi
 22f:	ff c7                	inc    edi
 231:	ff c3                	inc    ebx
 233:	ff c5                	inc    ebp
 235:	ff c6                	inc    esi
 237:	ff c7                	inc    edi
 239:	ff c3                	inc    ebx
 23b:	ff c5                	inc    ebp
 23d:	ff c6                	inc    esi
 23f:	ff c7                	inc    edi
 241:	ff c3                	inc    ebx
 243:	ff c5                	inc    ebp
 245:	ff c6                	inc    esi
 247:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 24a:	ff c3                	inc    ebx
 24c:	ff c5                	inc    ebp
 24e:	ff c6                	inc    esi
 250:	ff c7                	inc    edi
 252:	ff c3                	inc    ebx
 254:	ff c5                	inc    ebp
 256:	ff c6                	inc    esi
 258:	ff c7                	inc    edi
 25a:	ff c3                	inc    ebx
 25c:	ff c5                	inc    ebp
 25e:	ff c6                	inc    esi
 260:	ff c7                	inc    edi
 262:	ff c3                	inc    ebx
 264:	ff c5                	inc    ebp
 266:	ff c6                	inc    esi
 268:	ff c7                	inc    edi
 26a:	ff c3                	inc    ebx
 26c:	ff c5                	inc    ebp
 26e:	ff c6                	inc    esi
 270:	ff c7                	inc    edi
 272:	ff c3                	inc    ebx
 274:	ff c5                	inc    ebp
 276:	ff c6                	inc    esi
 278:	ff c7                	inc    edi
 27a:	ff c3                	inc    ebx
 27c:	ff c5                	inc    ebp
 27e:	ff c6                	inc    esi
 280:	ff c7                	inc    edi
 282:	ff c3                	inc    ebx
 284:	ff c5                	inc    ebp
 286:	ff c6                	inc    esi
 288:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 28b:	ff c3                	inc    ebx
 28d:	ff c5                	inc    ebp
 28f:	ff c6                	inc    esi
 291:	ff c7                	inc    edi
 293:	ff c3                	inc    ebx
 295:	ff c5                	inc    ebp
 297:	ff c6                	inc    esi
 299:	ff c7                	inc    edi
 29b:	ff c3                	inc    ebx
 29d:	ff c5                	inc    ebp
 29f:	ff c6                	inc    esi
 2a1:	ff c7                	inc    edi
 2a3:	ff c3                	inc    ebx
 2a5:	ff c5                	inc    ebp
 2a7:	ff c6                	inc    esi
 2a9:	ff c7                	inc    edi
 2ab:	ff c3                	inc    ebx
 2ad:	ff c5                	inc    ebp
 2af:	ff c6                	inc    esi
 2b1:	ff c7                	inc    edi
 2b3:	ff c3                	inc    ebx
 2b5:	ff c5                	inc    ebp
 2b7:	ff c6                	inc    esi
 2b9:	ff c7                	inc    edi
 2bb:	ff c3                	inc    ebx
 2bd:	ff c5                	inc    ebp
 2bf:	ff c6                	inc    esi
 2c1:	ff c7                	inc    edi
 2c3:	ff c3                	inc    ebx
 2c5:	ff c5                	inc    ebp
 2c7:	ff c6                	inc    esi
 2c9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 2cc:	ff c3                	inc    ebx
 2ce:	ff c5                	inc    ebp
 2d0:	ff c6                	inc    esi
 2d2:	ff c7                	inc    edi
 2d4:	ff c3                	inc    ebx
 2d6:	ff c5                	inc    ebp
 2d8:	ff c6                	inc    esi
 2da:	ff c7                	inc    edi
 2dc:	ff c3                	inc    ebx
 2de:	ff c5                	inc    ebp
 2e0:	ff c6                	inc    esi
 2e2:	ff c7                	inc    edi
 2e4:	ff c3                	inc    ebx
 2e6:	ff c5                	inc    ebp
 2e8:	ff c6                	inc    esi
 2ea:	ff c7                	inc    edi
 2ec:	ff c3                	inc    ebx
 2ee:	ff c5                	inc    ebp
 2f0:	ff c6                	inc    esi
 2f2:	ff c7                	inc    edi
 2f4:	ff c3                	inc    ebx
 2f6:	ff c5                	inc    ebp
 2f8:	ff c6                	inc    esi
 2fa:	ff c7                	inc    edi
 2fc:	ff c3                	inc    ebx
 2fe:	ff c5                	inc    ebp
 300:	ff c6                	inc    esi
 302:	ff c7                	inc    edi
 304:	ff c3                	inc    ebx
 306:	ff c5                	inc    ebp
 308:	ff c6                	inc    esi
 30a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 30d:	ff c3                	inc    ebx
 30f:	ff c5                	inc    ebp
 311:	ff c6                	inc    esi
 313:	ff c7                	inc    edi
 315:	ff c3                	inc    ebx
 317:	ff c5                	inc    ebp
 319:	ff c6                	inc    esi
 31b:	ff c7                	inc    edi
 31d:	ff c3                	inc    ebx
 31f:	ff c5                	inc    ebp
 321:	ff c6                	inc    esi
 323:	ff c7                	inc    edi
 325:	ff c3                	inc    ebx
 327:	ff c5                	inc    ebp
 329:	ff c6                	inc    esi
 32b:	ff c7                	inc    edi
 32d:	ff c3                	inc    ebx
 32f:	ff c5                	inc    ebp
 331:	ff c6                	inc    esi
 333:	ff c7                	inc    edi
 335:	ff c3                	inc    ebx
 337:	ff c5                	inc    ebp
 339:	ff c6                	inc    esi
 33b:	ff c7                	inc    edi
 33d:	ff c3                	inc    ebx
 33f:	ff c5                	inc    ebp
 341:	ff c6                	inc    esi
 343:	ff c7                	inc    edi
 345:	ff c3                	inc    ebx
 347:	ff c5                	inc    ebp
 349:	ff c6                	inc    esi
 34b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 34e:	ff c3                	inc    ebx
 350:	ff c5                	inc    ebp
 352:	ff c6                	inc    esi
 354:	ff c7                	inc    edi
 356:	ff c3                	inc    ebx
 358:	ff c5                	inc    ebp
 35a:	ff c6                	inc    esi
 35c:	ff c7                	inc    edi
 35e:	ff c3                	inc    ebx
 360:	ff c5                	inc    ebp
 362:	ff c6                	inc    esi
 364:	ff c7                	inc    edi
 366:	ff c3                	inc    ebx
 368:	ff c5                	inc    ebp
 36a:	ff c6                	inc    esi
 36c:	ff c7                	inc    edi
 36e:	ff c3                	inc    ebx
 370:	ff c5                	inc    ebp
 372:	ff c6                	inc    esi
 374:	ff c7                	inc    edi
 376:	ff c3                	inc    ebx
 378:	ff c5                	inc    ebp
 37a:	ff c6                	inc    esi
 37c:	ff c7                	inc    edi
 37e:	ff c3                	inc    ebx
 380:	ff c5                	inc    ebp
 382:	ff c6                	inc    esi
 384:	ff c7                	inc    edi
 386:	ff c3                	inc    ebx
 388:	ff c5                	inc    ebp
 38a:	ff c6                	inc    esi
 38c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 38f:	ff c3                	inc    ebx
 391:	ff c5                	inc    ebp
 393:	ff c6                	inc    esi
 395:	ff c7                	inc    edi
 397:	ff c3                	inc    ebx
 399:	ff c5                	inc    ebp
 39b:	ff c6                	inc    esi
 39d:	ff c7                	inc    edi
 39f:	ff c3                	inc    ebx
 3a1:	ff c5                	inc    ebp
 3a3:	ff c6                	inc    esi
 3a5:	ff c7                	inc    edi
 3a7:	ff c3                	inc    ebx
 3a9:	ff c5                	inc    ebp
 3ab:	ff c6                	inc    esi
 3ad:	ff c7                	inc    edi
 3af:	ff c3                	inc    ebx
 3b1:	ff c5                	inc    ebp
 3b3:	ff c6                	inc    esi
 3b5:	ff c7                	inc    edi
 3b7:	ff c3                	inc    ebx
 3b9:	ff c5                	inc    ebp
 3bb:	ff c6                	inc    esi
 3bd:	ff c7                	inc    edi
 3bf:	ff c3                	inc    ebx
 3c1:	ff c5                	inc    ebp
 3c3:	ff c6                	inc    esi
 3c5:	ff c7                	inc    edi
 3c7:	ff c3                	inc    ebx
 3c9:	ff c5                	inc    ebp
 3cb:	ff c6                	inc    esi
 3cd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 3d0:	ff c3                	inc    ebx
 3d2:	ff c5                	inc    ebp
 3d4:	ff c6                	inc    esi
 3d6:	ff c7                	inc    edi
 3d8:	ff c3                	inc    ebx
 3da:	ff c5                	inc    ebp
 3dc:	ff c6                	inc    esi
 3de:	ff c7                	inc    edi
 3e0:	ff c3                	inc    ebx
 3e2:	ff c5                	inc    ebp
 3e4:	ff c6                	inc    esi
 3e6:	ff c7                	inc    edi
 3e8:	ff c3                	inc    ebx
 3ea:	ff c5                	inc    ebp
 3ec:	ff c6                	inc    esi
 3ee:	ff c7                	inc    edi
 3f0:	ff c3                	inc    ebx
 3f2:	ff c5                	inc    ebp
 3f4:	ff c6                	inc    esi
 3f6:	ff c7                	inc    edi
 3f8:	ff c3                	inc    ebx
 3fa:	ff c5                	inc    ebp
 3fc:	ff c6                	inc    esi
 3fe:	ff c7                	inc    edi
 400:	ff c3                	inc    ebx
 402:	ff c5                	inc    ebp
 404:	ff c6                	inc    esi
 406:	ff c7                	inc    edi
 408:	ff c3                	inc    ebx
 40a:	ff c5                	inc    ebp
 40c:	ff c6                	inc    esi
 40e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 411:	ff c3                	inc    ebx
 413:	ff c5                	inc    ebp
 415:	ff c6                	inc    esi
 417:	ff c7                	inc    edi
 419:	ff c3                	inc    ebx
 41b:	ff c5                	inc    ebp
 41d:	ff c6                	inc    esi
 41f:	ff c7                	inc    edi
 421:	ff c3                	inc    ebx
 423:	ff c5                	inc    ebp
 425:	ff c6                	inc    esi
 427:	ff c7                	inc    edi
 429:	ff c3                	inc    ebx
 42b:	ff c5                	inc    ebp
 42d:	ff c6                	inc    esi
 42f:	ff c7                	inc    edi
 431:	ff c3                	inc    ebx
 433:	ff c5                	inc    ebp
 435:	ff c6                	inc    esi
 437:	ff c7                	inc    edi
 439:	ff c3                	inc    ebx
 43b:	ff c5                	inc    ebp
 43d:	ff c6                	inc    esi
 43f:	ff c7                	inc    edi
 441:	ff c3                	inc    ebx
 443:	ff c5                	inc    ebp
 445:	ff c6                	inc    esi
 447:	ff c7                	inc    edi
 449:	ff c3                	inc    ebx
 44b:	ff c5                	inc    ebp
 44d:	ff c6                	inc    esi
 44f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 452:	ff c3                	inc    ebx
 454:	ff c5                	inc    ebp
 456:	ff c6                	inc    esi
 458:	ff c7                	inc    edi
 45a:	ff c3                	inc    ebx
 45c:	ff c5                	inc    ebp
 45e:	ff c6                	inc    esi
 460:	ff c7                	inc    edi
 462:	ff c3                	inc    ebx
 464:	ff c5                	inc    ebp
 466:	ff c6                	inc    esi
 468:	ff c7                	inc    edi
 46a:	ff c3                	inc    ebx
 46c:	ff c5                	inc    ebp
 46e:	ff c6                	inc    esi
 470:	ff c7                	inc    edi
 472:	ff c3                	inc    ebx
 474:	ff c5                	inc    ebp
 476:	ff c6                	inc    esi
 478:	ff c7                	inc    edi
 47a:	ff c3                	inc    ebx
 47c:	ff c5                	inc    ebp
 47e:	ff c6                	inc    esi
 480:	ff c7                	inc    edi
 482:	ff c3                	inc    ebx
 484:	ff c5                	inc    ebp
 486:	ff c6                	inc    esi
 488:	ff c7                	inc    edi
 48a:	ff c3                	inc    ebx
 48c:	ff c5                	inc    ebp
 48e:	ff c6                	inc    esi
 490:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 493:	ff c3                	inc    ebx
 495:	ff c5                	inc    ebp
 497:	ff c6                	inc    esi
 499:	ff c7                	inc    edi
 49b:	ff c3                	inc    ebx
 49d:	ff c5                	inc    ebp
 49f:	ff c6                	inc    esi
 4a1:	ff c7                	inc    edi
 4a3:	ff c3                	inc    ebx
 4a5:	ff c5                	inc    ebp
 4a7:	ff c6                	inc    esi
 4a9:	ff c7                	inc    edi
 4ab:	ff c3                	inc    ebx
 4ad:	ff c5                	inc    ebp
 4af:	ff c6                	inc    esi
 4b1:	ff c7                	inc    edi
 4b3:	ff c3                	inc    ebx
 4b5:	ff c5                	inc    ebp
 4b7:	ff c6                	inc    esi
 4b9:	ff c7                	inc    edi
 4bb:	ff c3                	inc    ebx
 4bd:	ff c5                	inc    ebp
 4bf:	ff c6                	inc    esi
 4c1:	ff c7                	inc    edi
 4c3:	ff c3                	inc    ebx
 4c5:	ff c5                	inc    ebp
 4c7:	ff c6                	inc    esi
 4c9:	ff c7                	inc    edi
 4cb:	ff c3                	inc    ebx
 4cd:	ff c5                	inc    ebp
 4cf:	ff c6                	inc    esi
 4d1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 4d4:	ff c3                	inc    ebx
 4d6:	ff c5                	inc    ebp
 4d8:	ff c6                	inc    esi
 4da:	ff c7                	inc    edi
 4dc:	ff c3                	inc    ebx
 4de:	ff c5                	inc    ebp
 4e0:	ff c6                	inc    esi
 4e2:	ff c7                	inc    edi
 4e4:	ff c3                	inc    ebx
 4e6:	ff c5                	inc    ebp
 4e8:	ff c6                	inc    esi
 4ea:	ff c7                	inc    edi
 4ec:	ff c3                	inc    ebx
 4ee:	ff c5                	inc    ebp
 4f0:	ff c6                	inc    esi
 4f2:	ff c7                	inc    edi
 4f4:	ff c3                	inc    ebx
 4f6:	ff c5                	inc    ebp
 4f8:	ff c6                	inc    esi
 4fa:	ff c7                	inc    edi
 4fc:	ff c3                	inc    ebx
 4fe:	ff c5                	inc    ebp
 500:	ff c6                	inc    esi
 502:	ff c7                	inc    edi
 504:	ff c3                	inc    ebx
 506:	ff c5                	inc    ebp
 508:	ff c6                	inc    esi
 50a:	ff c7                	inc    edi
 50c:	ff c3                	inc    ebx
 50e:	ff c5                	inc    ebp
 510:	ff c6                	inc    esi
 512:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 515:	ff c3                	inc    ebx
 517:	ff c5                	inc    ebp
 519:	ff c6                	inc    esi
 51b:	ff c7                	inc    edi
 51d:	ff c3                	inc    ebx
 51f:	ff c5                	inc    ebp
 521:	ff c6                	inc    esi
 523:	ff c7                	inc    edi
 525:	ff c3                	inc    ebx
 527:	ff c5                	inc    ebp
 529:	ff c6                	inc    esi
 52b:	ff c7                	inc    edi
 52d:	ff c3                	inc    ebx
 52f:	ff c5                	inc    ebp
 531:	ff c6                	inc    esi
 533:	ff c7                	inc    edi
 535:	ff c3                	inc    ebx
 537:	ff c5                	inc    ebp
 539:	ff c6                	inc    esi
 53b:	ff c7                	inc    edi
 53d:	ff c3                	inc    ebx
 53f:	ff c5                	inc    ebp
 541:	ff c6                	inc    esi
 543:	ff c7                	inc    edi
 545:	ff c3                	inc    ebx
 547:	ff c5                	inc    ebp
 549:	ff c6                	inc    esi
 54b:	ff c7                	inc    edi
 54d:	ff c3                	inc    ebx
 54f:	ff c5                	inc    ebp
 551:	ff c6                	inc    esi
 553:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 556:	ff c3                	inc    ebx
 558:	ff c5                	inc    ebp
 55a:	ff c6                	inc    esi
 55c:	ff c7                	inc    edi
 55e:	ff c3                	inc    ebx
 560:	ff c5                	inc    ebp
 562:	ff c6                	inc    esi
 564:	ff c7                	inc    edi
 566:	ff c3                	inc    ebx
 568:	ff c5                	inc    ebp
 56a:	ff c6                	inc    esi
 56c:	ff c7                	inc    edi
 56e:	ff c3                	inc    ebx
 570:	ff c5                	inc    ebp
 572:	ff c6                	inc    esi
 574:	ff c7                	inc    edi
 576:	ff c3                	inc    ebx
 578:	ff c5                	inc    ebp
 57a:	ff c6                	inc    esi
 57c:	ff c7                	inc    edi
 57e:	ff c3                	inc    ebx
 580:	ff c5                	inc    ebp
 582:	ff c6                	inc    esi
 584:	ff c7                	inc    edi
 586:	ff c3                	inc    ebx
 588:	ff c5                	inc    ebp
 58a:	ff c6                	inc    esi
 58c:	ff c7                	inc    edi
 58e:	ff c3                	inc    ebx
 590:	ff c5                	inc    ebp
 592:	ff c6                	inc    esi
 594:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 597:	ff c3                	inc    ebx
 599:	ff c5                	inc    ebp
 59b:	ff c6                	inc    esi
 59d:	ff c7                	inc    edi
 59f:	ff c3                	inc    ebx
 5a1:	ff c5                	inc    ebp
 5a3:	ff c6                	inc    esi
 5a5:	ff c7                	inc    edi
 5a7:	ff c3                	inc    ebx
 5a9:	ff c5                	inc    ebp
 5ab:	ff c6                	inc    esi
 5ad:	ff c7                	inc    edi
 5af:	ff c3                	inc    ebx
 5b1:	ff c5                	inc    ebp
 5b3:	ff c6                	inc    esi
 5b5:	ff c7                	inc    edi
 5b7:	ff c3                	inc    ebx
 5b9:	ff c5                	inc    ebp
 5bb:	ff c6                	inc    esi
 5bd:	ff c7                	inc    edi
 5bf:	ff c3                	inc    ebx
 5c1:	ff c5                	inc    ebp
 5c3:	ff c6                	inc    esi
 5c5:	ff c7                	inc    edi
 5c7:	ff c3                	inc    ebx
 5c9:	ff c5                	inc    ebp
 5cb:	ff c6                	inc    esi
 5cd:	ff c7                	inc    edi
 5cf:	ff c3                	inc    ebx
 5d1:	ff c5                	inc    ebp
 5d3:	ff c6                	inc    esi
 5d5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 5d8:	ff c3                	inc    ebx
 5da:	ff c5                	inc    ebp
 5dc:	ff c6                	inc    esi
 5de:	ff c7                	inc    edi
 5e0:	ff c3                	inc    ebx
 5e2:	ff c5                	inc    ebp
 5e4:	ff c6                	inc    esi
 5e6:	ff c7                	inc    edi
 5e8:	ff c3                	inc    ebx
 5ea:	ff c5                	inc    ebp
 5ec:	ff c6                	inc    esi
 5ee:	ff c7                	inc    edi
 5f0:	ff c3                	inc    ebx
 5f2:	ff c5                	inc    ebp
 5f4:	ff c6                	inc    esi
 5f6:	ff c7                	inc    edi
 5f8:	ff c3                	inc    ebx
 5fa:	ff c5                	inc    ebp
 5fc:	ff c6                	inc    esi
 5fe:	ff c7                	inc    edi
 600:	ff c3                	inc    ebx
 602:	ff c5                	inc    ebp
 604:	ff c6                	inc    esi
 606:	ff c7                	inc    edi
 608:	ff c3                	inc    ebx
 60a:	ff c5                	inc    ebp
 60c:	ff c6                	inc    esi
 60e:	ff c7                	inc    edi
 610:	ff c3                	inc    ebx
 612:	ff c5                	inc    ebp
 614:	ff c6                	inc    esi
 616:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 619:	ff c3                	inc    ebx
 61b:	ff c5                	inc    ebp
 61d:	ff c6                	inc    esi
 61f:	ff c7                	inc    edi
 621:	ff c3                	inc    ebx
 623:	ff c5                	inc    ebp
 625:	ff c6                	inc    esi
 627:	ff c7                	inc    edi
 629:	ff c3                	inc    ebx
 62b:	ff c5                	inc    ebp
 62d:	ff c6                	inc    esi
 62f:	ff c7                	inc    edi
 631:	ff c3                	inc    ebx
 633:	ff c5                	inc    ebp
 635:	ff c6                	inc    esi
 637:	ff c7                	inc    edi
 639:	ff c3                	inc    ebx
 63b:	ff c5                	inc    ebp
 63d:	ff c6                	inc    esi
 63f:	ff c7                	inc    edi
 641:	ff c3                	inc    ebx
 643:	ff c5                	inc    ebp
 645:	ff c6                	inc    esi
 647:	ff c7                	inc    edi
 649:	ff c3                	inc    ebx
 64b:	ff c5                	inc    ebp
 64d:	ff c6                	inc    esi
 64f:	ff c7                	inc    edi
 651:	ff c3                	inc    ebx
 653:	ff c5                	inc    ebp
 655:	ff c6                	inc    esi
 657:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 65a:	ff c3                	inc    ebx
 65c:	ff c5                	inc    ebp
 65e:	ff c6                	inc    esi
 660:	ff c7                	inc    edi
 662:	ff c3                	inc    ebx
 664:	ff c5                	inc    ebp
 666:	ff c6                	inc    esi
 668:	ff c7                	inc    edi
 66a:	ff c3                	inc    ebx
 66c:	ff c5                	inc    ebp
 66e:	ff c6                	inc    esi
 670:	ff c7                	inc    edi
 672:	ff c3                	inc    ebx
 674:	ff c5                	inc    ebp
 676:	ff c6                	inc    esi
 678:	ff c7                	inc    edi
 67a:	ff c3                	inc    ebx
 67c:	ff c5                	inc    ebp
 67e:	ff c6                	inc    esi
 680:	ff c7                	inc    edi
 682:	ff c3                	inc    ebx
 684:	ff c5                	inc    ebp
 686:	ff c6                	inc    esi
 688:	ff c7                	inc    edi
 68a:	ff c3                	inc    ebx
 68c:	ff c5                	inc    ebp
 68e:	ff c6                	inc    esi
 690:	ff c7                	inc    edi
 692:	ff c3                	inc    ebx
 694:	ff c5                	inc    ebp
 696:	ff c6                	inc    esi
 698:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 69b:	ff c3                	inc    ebx
 69d:	ff c5                	inc    ebp
 69f:	ff c6                	inc    esi
 6a1:	ff c7                	inc    edi
 6a3:	ff c3                	inc    ebx
 6a5:	ff c5                	inc    ebp
 6a7:	ff c6                	inc    esi
 6a9:	ff c7                	inc    edi
 6ab:	ff c3                	inc    ebx
 6ad:	ff c5                	inc    ebp
 6af:	ff c6                	inc    esi
 6b1:	ff c7                	inc    edi
 6b3:	ff c3                	inc    ebx
 6b5:	ff c5                	inc    ebp
 6b7:	ff c6                	inc    esi
 6b9:	ff c7                	inc    edi
 6bb:	ff c3                	inc    ebx
 6bd:	ff c5                	inc    ebp
 6bf:	ff c6                	inc    esi
 6c1:	ff c7                	inc    edi
 6c3:	ff c3                	inc    ebx
 6c5:	ff c5                	inc    ebp
 6c7:	ff c6                	inc    esi
 6c9:	ff c7                	inc    edi
 6cb:	ff c3                	inc    ebx
 6cd:	ff c5                	inc    ebp
 6cf:	ff c6                	inc    esi
 6d1:	ff c7                	inc    edi
 6d3:	ff c3                	inc    ebx
 6d5:	ff c5                	inc    ebp
 6d7:	ff c6                	inc    esi
 6d9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 6dc:	ff c3                	inc    ebx
 6de:	ff c5                	inc    ebp
 6e0:	ff c6                	inc    esi
 6e2:	ff c7                	inc    edi
 6e4:	ff c3                	inc    ebx
 6e6:	ff c5                	inc    ebp
 6e8:	ff c6                	inc    esi
 6ea:	ff c7                	inc    edi
 6ec:	ff c3                	inc    ebx
 6ee:	ff c5                	inc    ebp
 6f0:	ff c6                	inc    esi
 6f2:	ff c7                	inc    edi
 6f4:	ff c3                	inc    ebx
 6f6:	ff c5                	inc    ebp
 6f8:	ff c6                	inc    esi
 6fa:	ff c7                	inc    edi
 6fc:	ff c3                	inc    ebx
 6fe:	ff c5                	inc    ebp
 700:	ff c6                	inc    esi
 702:	ff c7                	inc    edi
 704:	ff c3                	inc    ebx
 706:	ff c5                	inc    ebp
 708:	ff c6                	inc    esi
 70a:	ff c7                	inc    edi
 70c:	ff c3                	inc    ebx
 70e:	ff c5                	inc    ebp
 710:	ff c6                	inc    esi
 712:	ff c7                	inc    edi
 714:	ff c3                	inc    ebx
 716:	ff c5                	inc    ebp
 718:	ff c6                	inc    esi
 71a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 71d:	ff c3                	inc    ebx
 71f:	ff c5                	inc    ebp
 721:	ff c6                	inc    esi
 723:	ff c7                	inc    edi
 725:	ff c3                	inc    ebx
 727:	ff c5                	inc    ebp
 729:	ff c6                	inc    esi
 72b:	ff c7                	inc    edi
 72d:	ff c3                	inc    ebx
 72f:	ff c5                	inc    ebp
 731:	ff c6                	inc    esi
 733:	ff c7                	inc    edi
 735:	ff c3                	inc    ebx
 737:	ff c5                	inc    ebp
 739:	ff c6                	inc    esi
 73b:	ff c7                	inc    edi
 73d:	ff c3                	inc    ebx
 73f:	ff c5                	inc    ebp
 741:	ff c6                	inc    esi
 743:	ff c7                	inc    edi
 745:	ff c3                	inc    ebx
 747:	ff c5                	inc    ebp
 749:	ff c6                	inc    esi
 74b:	ff c7                	inc    edi
 74d:	ff c3                	inc    ebx
 74f:	ff c5                	inc    ebp
 751:	ff c6                	inc    esi
 753:	ff c7                	inc    edi
 755:	ff c3                	inc    ebx
 757:	ff c5                	inc    ebp
 759:	ff c6                	inc    esi
 75b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 75e:	ff c3                	inc    ebx
 760:	ff c5                	inc    ebp
 762:	ff c6                	inc    esi
 764:	ff c7                	inc    edi
 766:	ff c3                	inc    ebx
 768:	ff c5                	inc    ebp
 76a:	ff c6                	inc    esi
 76c:	ff c7                	inc    edi
 76e:	ff c3                	inc    ebx
 770:	ff c5                	inc    ebp
 772:	ff c6                	inc    esi
 774:	ff c7                	inc    edi
 776:	ff c3                	inc    ebx
 778:	ff c5                	inc    ebp
 77a:	ff c6                	inc    esi
 77c:	ff c7                	inc    edi
 77e:	ff c3                	inc    ebx
 780:	ff c5                	inc    ebp
 782:	ff c6                	inc    esi
 784:	ff c7                	inc    edi
 786:	ff c3                	inc    ebx
 788:	ff c5                	inc    ebp
 78a:	ff c6                	inc    esi
 78c:	ff c7                	inc    edi
 78e:	ff c3                	inc    ebx
 790:	ff c5                	inc    ebp
 792:	ff c6                	inc    esi
 794:	ff c7                	inc    edi
 796:	ff c3                	inc    ebx
 798:	ff c5                	inc    ebp
 79a:	ff c6                	inc    esi
 79c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 79f:	ff c3                	inc    ebx
 7a1:	ff c5                	inc    ebp
 7a3:	ff c6                	inc    esi
 7a5:	ff c7                	inc    edi
 7a7:	ff c3                	inc    ebx
 7a9:	ff c5                	inc    ebp
 7ab:	ff c6                	inc    esi
 7ad:	ff c7                	inc    edi
 7af:	ff c3                	inc    ebx
 7b1:	ff c5                	inc    ebp
 7b3:	ff c6                	inc    esi
 7b5:	ff c7                	inc    edi
 7b7:	ff c3                	inc    ebx
 7b9:	ff c5                	inc    ebp
 7bb:	ff c6                	inc    esi
 7bd:	ff c7                	inc    edi
 7bf:	ff c3                	inc    ebx
 7c1:	ff c5                	inc    ebp
 7c3:	ff c6                	inc    esi
 7c5:	ff c7                	inc    edi
 7c7:	ff c3                	inc    ebx
 7c9:	ff c5                	inc    ebp
 7cb:	ff c6                	inc    esi
 7cd:	ff c7                	inc    edi
 7cf:	ff c3                	inc    ebx
 7d1:	ff c5                	inc    ebp
 7d3:	ff c6                	inc    esi
 7d5:	ff c7                	inc    edi
 7d7:	ff c3                	inc    ebx
 7d9:	ff c5                	inc    ebp
 7db:	ff c6                	inc    esi
 7dd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 7e0:	ff c3                	inc    ebx
 7e2:	ff c5                	inc    ebp
 7e4:	ff c6                	inc    esi
 7e6:	ff c7                	inc    edi
 7e8:	ff c3                	inc    ebx
 7ea:	ff c5                	inc    ebp
 7ec:	ff c6                	inc    esi
 7ee:	ff c7                	inc    edi
 7f0:	ff c3                	inc    ebx
 7f2:	ff c5                	inc    ebp
 7f4:	ff c6                	inc    esi
 7f6:	ff c7                	inc    edi
 7f8:	ff c3                	inc    ebx
 7fa:	ff c5                	inc    ebp
 7fc:	ff c6                	inc    esi
 7fe:	ff c7                	inc    edi
 800:	ff c3                	inc    ebx
 802:	ff c5                	inc    ebp
 804:	ff c6                	inc    esi
 806:	ff c7                	inc    edi
 808:	ff c3                	inc    ebx
 80a:	ff c5                	inc    ebp
 80c:	ff c6                	inc    esi
 80e:	ff c7                	inc    edi
 810:	ff c3                	inc    ebx
 812:	ff c5                	inc    ebp
 814:	ff c6                	inc    esi
 816:	ff c7                	inc    edi
 818:	ff c3                	inc    ebx
 81a:	ff c5                	inc    ebp
 81c:	ff c6                	inc    esi
 81e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 821:	ff c3                	inc    ebx
 823:	ff c5                	inc    ebp
 825:	ff c6                	inc    esi
 827:	ff c7                	inc    edi
 829:	ff c3                	inc    ebx
 82b:	ff c5                	inc    ebp
 82d:	ff c6                	inc    esi
 82f:	ff c7                	inc    edi
 831:	ff c3                	inc    ebx
 833:	ff c5                	inc    ebp
 835:	ff c6                	inc    esi
 837:	ff c7                	inc    edi
 839:	ff c3                	inc    ebx
 83b:	ff c5                	inc    ebp
 83d:	ff c6                	inc    esi
 83f:	ff c7                	inc    edi
 841:	ff c3                	inc    ebx
 843:	ff c5                	inc    ebp
 845:	ff c6                	inc    esi
 847:	ff c7                	inc    edi
 849:	ff c3                	inc    ebx
 84b:	ff c5                	inc    ebp
 84d:	ff c6                	inc    esi
 84f:	ff c7                	inc    edi
 851:	ff c3                	inc    ebx
 853:	ff c5                	inc    ebp
 855:	ff c6                	inc    esi
 857:	ff c7                	inc    edi
 859:	ff c3                	inc    ebx
 85b:	ff c5                	inc    ebp
 85d:	ff c6                	inc    esi
 85f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 862:	ff c3                	inc    ebx
 864:	ff c5                	inc    ebp
 866:	ff c6                	inc    esi
 868:	ff c7                	inc    edi
 86a:	ff c3                	inc    ebx
 86c:	ff c5                	inc    ebp
 86e:	ff c6                	inc    esi
 870:	ff c7                	inc    edi
 872:	ff c3                	inc    ebx
 874:	ff c5                	inc    ebp
 876:	ff c6                	inc    esi
 878:	ff c7                	inc    edi
 87a:	ff c3                	inc    ebx
 87c:	ff c5                	inc    ebp
 87e:	ff c6                	inc    esi
 880:	ff c7                	inc    edi
 882:	ff c3                	inc    ebx
 884:	ff c5                	inc    ebp
 886:	ff c6                	inc    esi
 888:	ff c7                	inc    edi
 88a:	ff c3                	inc    ebx
 88c:	ff c5                	inc    ebp
 88e:	ff c6                	inc    esi
 890:	ff c7                	inc    edi
 892:	ff c3                	inc    ebx
 894:	ff c5                	inc    ebp
 896:	ff c6                	inc    esi
 898:	ff c7                	inc    edi
 89a:	ff c3                	inc    ebx
 89c:	ff c5                	inc    ebp
 89e:	ff c6                	inc    esi
 8a0:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 8a3:	ff c3                	inc    ebx
 8a5:	ff c5                	inc    ebp
 8a7:	ff c6                	inc    esi
 8a9:	ff c7                	inc    edi
 8ab:	ff c3                	inc    ebx
 8ad:	ff c5                	inc    ebp
 8af:	ff c6                	inc    esi
 8b1:	ff c7                	inc    edi
 8b3:	ff c3                	inc    ebx
 8b5:	ff c5                	inc    ebp
 8b7:	ff c6                	inc    esi
 8b9:	ff c7                	inc    edi
 8bb:	ff c3                	inc    ebx
 8bd:	ff c5                	inc    ebp
 8bf:	ff c6                	inc    esi
 8c1:	ff c7                	inc    edi
 8c3:	ff c3                	inc    ebx
 8c5:	ff c5                	inc    ebp
 8c7:	ff c6                	inc    esi
 8c9:	ff c7                	inc    edi
 8cb:	ff c3                	inc    ebx
 8cd:	ff c5                	inc    ebp
 8cf:	ff c6                	inc    esi
 8d1:	ff c7                	inc    edi
 8d3:	ff c3                	inc    ebx
 8d5:	ff c5                	inc    ebp
 8d7:	ff c6                	inc    esi
 8d9:	ff c7                	inc    edi
 8db:	ff c3                	inc    ebx
 8dd:	ff c5                	inc    ebp
 8df:	ff c6                	inc    esi
 8e1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 8e4:	ff c3                	inc    ebx
 8e6:	ff c5                	inc    ebp
 8e8:	ff c6                	inc    esi
 8ea:	ff c7                	inc    edi
 8ec:	ff c3                	inc    ebx
 8ee:	ff c5                	inc    ebp
 8f0:	ff c6                	inc    esi
 8f2:	ff c7                	inc    edi
 8f4:	ff c3                	inc    ebx
 8f6:	ff c5                	inc    ebp
 8f8:	ff c6                	inc    esi
 8fa:	ff c7                	inc    edi
 8fc:	ff c3                	inc    ebx
 8fe:	ff c5                	inc    ebp
 900:	ff c6                	inc    esi
 902:	ff c7                	inc    edi
 904:	ff c3                	inc    ebx
 906:	ff c5                	inc    ebp
 908:	ff c6                	inc    esi
 90a:	ff c7                	inc    edi
 90c:	ff c3                	inc    ebx
 90e:	ff c5                	inc    ebp
 910:	ff c6                	inc    esi
 912:	ff c7                	inc    edi
 914:	ff c3                	inc    ebx
 916:	ff c5                	inc    ebp
 918:	ff c6                	inc    esi
 91a:	ff c7                	inc    edi
 91c:	ff c3                	inc    ebx
 91e:	ff c5                	inc    ebp
 920:	ff c6                	inc    esi
 922:	83 e8 01             	sub    eax,0x1
 925:	0f 85 55 f7 ff ff    	jne    0x80
 92b:	66 90                	xchg   ax,ax
 92d:	66 90                	xchg   ax,ax
 92f:	66 90                	xchg   ax,ax
 931:	66 90                	xchg   ax,ax
 933:	66 90                	xchg   ax,ax
 935:	66 90                	xchg   ax,ax
 937:	66 90                	xchg   ax,ax
 939:	66 90                	xchg   ax,ax
 93b:	48 81 c4 a4 6a 00 00 	add    rsp,0x6aa4
 942:	41 59                	pop    r9
 944:	41 58                	pop    r8
 946:	5f                   	pop    rdi
 947:	5e                   	pop    rsi
 948:	5d                   	pop    rbp
 949:	5b                   	pop    rbx
 94a:	0f 77                	emms   
 94c:	c3                   	ret    
