
asm.bin:     file format binary


Disassembly of section .data:

0000000000000000 <.data>:
   0:	66 90                	xchg   ax,ax
   2:	66 90                	xchg   ax,ax
   4:	66 90                	xchg   ax,ax
   6:	66 90                	xchg   ax,ax
   8:	66 90                	xchg   ax,ax
   a:	66 90                	xchg   ax,ax
   c:	66 90                	xchg   ax,ax
   e:	66 90                	xchg   ax,ax
  10:	53                   	push   rbx
  11:	55                   	push   rbp
  12:	56                   	push   rsi
  13:	57                   	push   rdi
  14:	41 50                	push   r8
  16:	41 51                	push   r9
  18:	48 81 ec a4 6a 00 00 	sub    rsp,0x6aa4
  1f:	45 31 c0             	xor    r8d,r8d
  22:	4c 8d 0c 24          	lea    r9,[rsp]
  26:	48 b9 01 00 00 00 00 	movabs rcx,0x1
  2d:	00 00 00 
  30:	48 ba 02 00 00 00 00 	movabs rdx,0x2
  37:	00 00 00 
  3a:	48 b8 00 20 00 00 00 	movabs rax,0x2000
  41:	00 00 00 
  44:	48 83 eb 00          	sub    rbx,0x0
  48:	48 83 ed 00          	sub    rbp,0x0
  4c:	48 83 ee 00          	sub    rsi,0x0
  50:	48 83 ef 00          	sub    rdi,0x0
  54:	49 83 e8 00          	sub    r8,0x0
  58:	49 83 e9 00          	sub    r9,0x0
  5c:	49 83 ea 00          	sub    r10,0x0
  60:	49 83 eb 00          	sub    r11,0x0
  64:	49 83 ec 00          	sub    r12,0x0
  68:	49 83 ed 00          	sub    r13,0x0
  6c:	49 83 ee 00          	sub    r14,0x0
  70:	49 83 ef 00          	sub    r15,0x0
  74:	90                   	nop
  75:	90                   	nop
  76:	90                   	nop
  77:	90                   	nop
  78:	90                   	nop
  79:	90                   	nop
  7a:	90                   	nop
  7b:	90                   	nop
  7c:	90                   	nop
  7d:	90                   	nop
  7e:	90                   	nop
  7f:	90                   	nop
  80:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
  83:	ff c3                	inc    ebx
  85:	ff c3                	inc    ebx
  87:	ff c3                	inc    ebx
  89:	ff c3                	inc    ebx
  8b:	ff c3                	inc    ebx
  8d:	ff c3                	inc    ebx
  8f:	ff c3                	inc    ebx
  91:	ff c3                	inc    ebx
  93:	ff c3                	inc    ebx
  95:	ff c3                	inc    ebx
  97:	ff c3                	inc    ebx
  99:	ff c3                	inc    ebx
  9b:	ff c3                	inc    ebx
  9d:	ff c3                	inc    ebx
  9f:	ff c3                	inc    ebx
  a1:	ff c3                	inc    ebx
  a3:	ff c3                	inc    ebx
  a5:	ff c3                	inc    ebx
  a7:	ff c3                	inc    ebx
  a9:	ff c3                	inc    ebx
  ab:	ff c3                	inc    ebx
  ad:	ff c3                	inc    ebx
  af:	ff c3                	inc    ebx
  b1:	ff c3                	inc    ebx
  b3:	ff c3                	inc    ebx
  b5:	ff c3                	inc    ebx
  b7:	ff c3                	inc    ebx
  b9:	ff c3                	inc    ebx
  bb:	ff c3                	inc    ebx
  bd:	ff c3                	inc    ebx
  bf:	ff c3                	inc    ebx
  c1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
  c4:	ff c3                	inc    ebx
  c6:	ff c3                	inc    ebx
  c8:	ff c3                	inc    ebx
  ca:	ff c3                	inc    ebx
  cc:	ff c3                	inc    ebx
  ce:	ff c3                	inc    ebx
  d0:	ff c3                	inc    ebx
  d2:	ff c3                	inc    ebx
  d4:	ff c3                	inc    ebx
  d6:	ff c3                	inc    ebx
  d8:	ff c3                	inc    ebx
  da:	ff c3                	inc    ebx
  dc:	ff c3                	inc    ebx
  de:	ff c3                	inc    ebx
  e0:	ff c3                	inc    ebx
  e2:	ff c3                	inc    ebx
  e4:	ff c3                	inc    ebx
  e6:	ff c3                	inc    ebx
  e8:	ff c3                	inc    ebx
  ea:	ff c3                	inc    ebx
  ec:	ff c3                	inc    ebx
  ee:	ff c3                	inc    ebx
  f0:	ff c3                	inc    ebx
  f2:	ff c3                	inc    ebx
  f4:	ff c3                	inc    ebx
  f6:	ff c3                	inc    ebx
  f8:	ff c3                	inc    ebx
  fa:	ff c3                	inc    ebx
  fc:	ff c3                	inc    ebx
  fe:	ff c3                	inc    ebx
 100:	ff c3                	inc    ebx
 102:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 105:	ff c3                	inc    ebx
 107:	ff c3                	inc    ebx
 109:	ff c3                	inc    ebx
 10b:	ff c3                	inc    ebx
 10d:	ff c3                	inc    ebx
 10f:	ff c3                	inc    ebx
 111:	ff c3                	inc    ebx
 113:	ff c3                	inc    ebx
 115:	ff c3                	inc    ebx
 117:	ff c3                	inc    ebx
 119:	ff c3                	inc    ebx
 11b:	ff c3                	inc    ebx
 11d:	ff c3                	inc    ebx
 11f:	ff c3                	inc    ebx
 121:	ff c3                	inc    ebx
 123:	ff c3                	inc    ebx
 125:	ff c3                	inc    ebx
 127:	ff c3                	inc    ebx
 129:	ff c3                	inc    ebx
 12b:	ff c3                	inc    ebx
 12d:	ff c3                	inc    ebx
 12f:	ff c3                	inc    ebx
 131:	ff c3                	inc    ebx
 133:	ff c3                	inc    ebx
 135:	ff c3                	inc    ebx
 137:	ff c3                	inc    ebx
 139:	ff c3                	inc    ebx
 13b:	ff c3                	inc    ebx
 13d:	ff c3                	inc    ebx
 13f:	ff c3                	inc    ebx
 141:	ff c3                	inc    ebx
 143:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 146:	ff c3                	inc    ebx
 148:	ff c3                	inc    ebx
 14a:	ff c3                	inc    ebx
 14c:	ff c3                	inc    ebx
 14e:	ff c3                	inc    ebx
 150:	ff c3                	inc    ebx
 152:	ff c3                	inc    ebx
 154:	ff c3                	inc    ebx
 156:	ff c3                	inc    ebx
 158:	ff c3                	inc    ebx
 15a:	ff c3                	inc    ebx
 15c:	ff c3                	inc    ebx
 15e:	ff c3                	inc    ebx
 160:	ff c3                	inc    ebx
 162:	ff c3                	inc    ebx
 164:	ff c3                	inc    ebx
 166:	ff c3                	inc    ebx
 168:	ff c3                	inc    ebx
 16a:	ff c3                	inc    ebx
 16c:	ff c3                	inc    ebx
 16e:	ff c3                	inc    ebx
 170:	ff c3                	inc    ebx
 172:	ff c3                	inc    ebx
 174:	ff c3                	inc    ebx
 176:	ff c3                	inc    ebx
 178:	ff c3                	inc    ebx
 17a:	ff c3                	inc    ebx
 17c:	ff c3                	inc    ebx
 17e:	ff c3                	inc    ebx
 180:	ff c3                	inc    ebx
 182:	ff c3                	inc    ebx
 184:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 187:	ff c3                	inc    ebx
 189:	ff c3                	inc    ebx
 18b:	ff c3                	inc    ebx
 18d:	ff c3                	inc    ebx
 18f:	ff c3                	inc    ebx
 191:	ff c3                	inc    ebx
 193:	ff c3                	inc    ebx
 195:	ff c3                	inc    ebx
 197:	ff c3                	inc    ebx
 199:	ff c3                	inc    ebx
 19b:	ff c3                	inc    ebx
 19d:	ff c3                	inc    ebx
 19f:	ff c3                	inc    ebx
 1a1:	ff c3                	inc    ebx
 1a3:	ff c3                	inc    ebx
 1a5:	ff c3                	inc    ebx
 1a7:	ff c3                	inc    ebx
 1a9:	ff c3                	inc    ebx
 1ab:	ff c3                	inc    ebx
 1ad:	ff c3                	inc    ebx
 1af:	ff c3                	inc    ebx
 1b1:	ff c3                	inc    ebx
 1b3:	ff c3                	inc    ebx
 1b5:	ff c3                	inc    ebx
 1b7:	ff c3                	inc    ebx
 1b9:	ff c3                	inc    ebx
 1bb:	ff c3                	inc    ebx
 1bd:	ff c3                	inc    ebx
 1bf:	ff c3                	inc    ebx
 1c1:	ff c3                	inc    ebx
 1c3:	ff c3                	inc    ebx
 1c5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 1c8:	ff c3                	inc    ebx
 1ca:	ff c3                	inc    ebx
 1cc:	ff c3                	inc    ebx
 1ce:	ff c3                	inc    ebx
 1d0:	ff c3                	inc    ebx
 1d2:	ff c3                	inc    ebx
 1d4:	ff c3                	inc    ebx
 1d6:	ff c3                	inc    ebx
 1d8:	ff c3                	inc    ebx
 1da:	ff c3                	inc    ebx
 1dc:	ff c3                	inc    ebx
 1de:	ff c3                	inc    ebx
 1e0:	ff c3                	inc    ebx
 1e2:	ff c3                	inc    ebx
 1e4:	ff c3                	inc    ebx
 1e6:	ff c3                	inc    ebx
 1e8:	ff c3                	inc    ebx
 1ea:	ff c3                	inc    ebx
 1ec:	ff c3                	inc    ebx
 1ee:	ff c3                	inc    ebx
 1f0:	ff c3                	inc    ebx
 1f2:	ff c3                	inc    ebx
 1f4:	ff c3                	inc    ebx
 1f6:	ff c3                	inc    ebx
 1f8:	ff c3                	inc    ebx
 1fa:	ff c3                	inc    ebx
 1fc:	ff c3                	inc    ebx
 1fe:	ff c3                	inc    ebx
 200:	ff c3                	inc    ebx
 202:	ff c3                	inc    ebx
 204:	ff c3                	inc    ebx
 206:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 209:	ff c3                	inc    ebx
 20b:	ff c3                	inc    ebx
 20d:	ff c3                	inc    ebx
 20f:	ff c3                	inc    ebx
 211:	ff c3                	inc    ebx
 213:	ff c3                	inc    ebx
 215:	ff c3                	inc    ebx
 217:	ff c3                	inc    ebx
 219:	ff c3                	inc    ebx
 21b:	ff c3                	inc    ebx
 21d:	ff c3                	inc    ebx
 21f:	ff c3                	inc    ebx
 221:	ff c3                	inc    ebx
 223:	ff c3                	inc    ebx
 225:	ff c3                	inc    ebx
 227:	ff c3                	inc    ebx
 229:	ff c3                	inc    ebx
 22b:	ff c3                	inc    ebx
 22d:	ff c3                	inc    ebx
 22f:	ff c3                	inc    ebx
 231:	ff c3                	inc    ebx
 233:	ff c3                	inc    ebx
 235:	ff c3                	inc    ebx
 237:	ff c3                	inc    ebx
 239:	ff c3                	inc    ebx
 23b:	ff c3                	inc    ebx
 23d:	ff c3                	inc    ebx
 23f:	ff c3                	inc    ebx
 241:	ff c3                	inc    ebx
 243:	ff c3                	inc    ebx
 245:	ff c3                	inc    ebx
 247:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 24a:	ff c3                	inc    ebx
 24c:	ff c3                	inc    ebx
 24e:	ff c3                	inc    ebx
 250:	ff c3                	inc    ebx
 252:	ff c3                	inc    ebx
 254:	ff c3                	inc    ebx
 256:	ff c3                	inc    ebx
 258:	ff c3                	inc    ebx
 25a:	ff c3                	inc    ebx
 25c:	ff c3                	inc    ebx
 25e:	ff c3                	inc    ebx
 260:	ff c3                	inc    ebx
 262:	ff c3                	inc    ebx
 264:	ff c3                	inc    ebx
 266:	ff c3                	inc    ebx
 268:	ff c3                	inc    ebx
 26a:	ff c3                	inc    ebx
 26c:	ff c3                	inc    ebx
 26e:	ff c3                	inc    ebx
 270:	ff c3                	inc    ebx
 272:	ff c3                	inc    ebx
 274:	ff c3                	inc    ebx
 276:	ff c3                	inc    ebx
 278:	ff c3                	inc    ebx
 27a:	ff c3                	inc    ebx
 27c:	ff c3                	inc    ebx
 27e:	ff c3                	inc    ebx
 280:	ff c3                	inc    ebx
 282:	ff c3                	inc    ebx
 284:	ff c3                	inc    ebx
 286:	ff c3                	inc    ebx
 288:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 28b:	ff c3                	inc    ebx
 28d:	ff c3                	inc    ebx
 28f:	ff c3                	inc    ebx
 291:	ff c3                	inc    ebx
 293:	ff c3                	inc    ebx
 295:	ff c3                	inc    ebx
 297:	ff c3                	inc    ebx
 299:	ff c3                	inc    ebx
 29b:	ff c3                	inc    ebx
 29d:	ff c3                	inc    ebx
 29f:	ff c3                	inc    ebx
 2a1:	ff c3                	inc    ebx
 2a3:	ff c3                	inc    ebx
 2a5:	ff c3                	inc    ebx
 2a7:	ff c3                	inc    ebx
 2a9:	ff c3                	inc    ebx
 2ab:	ff c3                	inc    ebx
 2ad:	ff c3                	inc    ebx
 2af:	ff c3                	inc    ebx
 2b1:	ff c3                	inc    ebx
 2b3:	ff c3                	inc    ebx
 2b5:	ff c3                	inc    ebx
 2b7:	ff c3                	inc    ebx
 2b9:	ff c3                	inc    ebx
 2bb:	ff c3                	inc    ebx
 2bd:	ff c3                	inc    ebx
 2bf:	ff c3                	inc    ebx
 2c1:	ff c3                	inc    ebx
 2c3:	ff c3                	inc    ebx
 2c5:	ff c3                	inc    ebx
 2c7:	ff c3                	inc    ebx
 2c9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 2cc:	ff c3                	inc    ebx
 2ce:	ff c3                	inc    ebx
 2d0:	ff c3                	inc    ebx
 2d2:	ff c3                	inc    ebx
 2d4:	ff c3                	inc    ebx
 2d6:	ff c3                	inc    ebx
 2d8:	ff c3                	inc    ebx
 2da:	ff c3                	inc    ebx
 2dc:	ff c3                	inc    ebx
 2de:	ff c3                	inc    ebx
 2e0:	ff c3                	inc    ebx
 2e2:	ff c3                	inc    ebx
 2e4:	ff c3                	inc    ebx
 2e6:	ff c3                	inc    ebx
 2e8:	ff c3                	inc    ebx
 2ea:	ff c3                	inc    ebx
 2ec:	ff c3                	inc    ebx
 2ee:	ff c3                	inc    ebx
 2f0:	ff c3                	inc    ebx
 2f2:	ff c3                	inc    ebx
 2f4:	ff c3                	inc    ebx
 2f6:	ff c3                	inc    ebx
 2f8:	ff c3                	inc    ebx
 2fa:	ff c3                	inc    ebx
 2fc:	ff c3                	inc    ebx
 2fe:	ff c3                	inc    ebx
 300:	ff c3                	inc    ebx
 302:	ff c3                	inc    ebx
 304:	ff c3                	inc    ebx
 306:	ff c3                	inc    ebx
 308:	ff c3                	inc    ebx
 30a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 30d:	ff c3                	inc    ebx
 30f:	ff c3                	inc    ebx
 311:	ff c3                	inc    ebx
 313:	ff c3                	inc    ebx
 315:	ff c3                	inc    ebx
 317:	ff c3                	inc    ebx
 319:	ff c3                	inc    ebx
 31b:	ff c3                	inc    ebx
 31d:	ff c3                	inc    ebx
 31f:	ff c3                	inc    ebx
 321:	ff c3                	inc    ebx
 323:	ff c3                	inc    ebx
 325:	ff c3                	inc    ebx
 327:	ff c3                	inc    ebx
 329:	ff c3                	inc    ebx
 32b:	ff c3                	inc    ebx
 32d:	ff c3                	inc    ebx
 32f:	ff c3                	inc    ebx
 331:	ff c3                	inc    ebx
 333:	ff c3                	inc    ebx
 335:	ff c3                	inc    ebx
 337:	ff c3                	inc    ebx
 339:	ff c3                	inc    ebx
 33b:	ff c3                	inc    ebx
 33d:	ff c3                	inc    ebx
 33f:	ff c3                	inc    ebx
 341:	ff c3                	inc    ebx
 343:	ff c3                	inc    ebx
 345:	ff c3                	inc    ebx
 347:	ff c3                	inc    ebx
 349:	ff c3                	inc    ebx
 34b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 34e:	ff c3                	inc    ebx
 350:	ff c3                	inc    ebx
 352:	ff c3                	inc    ebx
 354:	ff c3                	inc    ebx
 356:	ff c3                	inc    ebx
 358:	ff c3                	inc    ebx
 35a:	ff c3                	inc    ebx
 35c:	ff c3                	inc    ebx
 35e:	ff c3                	inc    ebx
 360:	ff c3                	inc    ebx
 362:	ff c3                	inc    ebx
 364:	ff c3                	inc    ebx
 366:	ff c3                	inc    ebx
 368:	ff c3                	inc    ebx
 36a:	ff c3                	inc    ebx
 36c:	ff c3                	inc    ebx
 36e:	ff c3                	inc    ebx
 370:	ff c3                	inc    ebx
 372:	ff c3                	inc    ebx
 374:	ff c3                	inc    ebx
 376:	ff c3                	inc    ebx
 378:	ff c3                	inc    ebx
 37a:	ff c3                	inc    ebx
 37c:	ff c3                	inc    ebx
 37e:	ff c3                	inc    ebx
 380:	ff c3                	inc    ebx
 382:	ff c3                	inc    ebx
 384:	ff c3                	inc    ebx
 386:	ff c3                	inc    ebx
 388:	ff c3                	inc    ebx
 38a:	ff c3                	inc    ebx
 38c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 38f:	ff c3                	inc    ebx
 391:	ff c3                	inc    ebx
 393:	ff c3                	inc    ebx
 395:	ff c3                	inc    ebx
 397:	ff c3                	inc    ebx
 399:	ff c3                	inc    ebx
 39b:	ff c3                	inc    ebx
 39d:	ff c3                	inc    ebx
 39f:	ff c3                	inc    ebx
 3a1:	ff c3                	inc    ebx
 3a3:	ff c3                	inc    ebx
 3a5:	ff c3                	inc    ebx
 3a7:	ff c3                	inc    ebx
 3a9:	ff c3                	inc    ebx
 3ab:	ff c3                	inc    ebx
 3ad:	ff c3                	inc    ebx
 3af:	ff c3                	inc    ebx
 3b1:	ff c3                	inc    ebx
 3b3:	ff c3                	inc    ebx
 3b5:	ff c3                	inc    ebx
 3b7:	ff c3                	inc    ebx
 3b9:	ff c3                	inc    ebx
 3bb:	ff c3                	inc    ebx
 3bd:	ff c3                	inc    ebx
 3bf:	ff c3                	inc    ebx
 3c1:	ff c3                	inc    ebx
 3c3:	ff c3                	inc    ebx
 3c5:	ff c3                	inc    ebx
 3c7:	ff c3                	inc    ebx
 3c9:	ff c3                	inc    ebx
 3cb:	ff c3                	inc    ebx
 3cd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 3d0:	ff c3                	inc    ebx
 3d2:	ff c3                	inc    ebx
 3d4:	ff c3                	inc    ebx
 3d6:	ff c3                	inc    ebx
 3d8:	ff c3                	inc    ebx
 3da:	ff c3                	inc    ebx
 3dc:	ff c3                	inc    ebx
 3de:	ff c3                	inc    ebx
 3e0:	ff c3                	inc    ebx
 3e2:	ff c3                	inc    ebx
 3e4:	ff c3                	inc    ebx
 3e6:	ff c3                	inc    ebx
 3e8:	ff c3                	inc    ebx
 3ea:	ff c3                	inc    ebx
 3ec:	ff c3                	inc    ebx
 3ee:	ff c3                	inc    ebx
 3f0:	ff c3                	inc    ebx
 3f2:	ff c3                	inc    ebx
 3f4:	ff c3                	inc    ebx
 3f6:	ff c3                	inc    ebx
 3f8:	ff c3                	inc    ebx
 3fa:	ff c3                	inc    ebx
 3fc:	ff c3                	inc    ebx
 3fe:	ff c3                	inc    ebx
 400:	ff c3                	inc    ebx
 402:	ff c3                	inc    ebx
 404:	ff c3                	inc    ebx
 406:	ff c3                	inc    ebx
 408:	ff c3                	inc    ebx
 40a:	ff c3                	inc    ebx
 40c:	ff c3                	inc    ebx
 40e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 411:	ff c3                	inc    ebx
 413:	ff c3                	inc    ebx
 415:	ff c3                	inc    ebx
 417:	ff c3                	inc    ebx
 419:	ff c3                	inc    ebx
 41b:	ff c3                	inc    ebx
 41d:	ff c3                	inc    ebx
 41f:	ff c3                	inc    ebx
 421:	ff c3                	inc    ebx
 423:	ff c3                	inc    ebx
 425:	ff c3                	inc    ebx
 427:	ff c3                	inc    ebx
 429:	ff c3                	inc    ebx
 42b:	ff c3                	inc    ebx
 42d:	ff c3                	inc    ebx
 42f:	ff c3                	inc    ebx
 431:	ff c3                	inc    ebx
 433:	ff c3                	inc    ebx
 435:	ff c3                	inc    ebx
 437:	ff c3                	inc    ebx
 439:	ff c3                	inc    ebx
 43b:	ff c3                	inc    ebx
 43d:	ff c3                	inc    ebx
 43f:	ff c3                	inc    ebx
 441:	ff c3                	inc    ebx
 443:	ff c3                	inc    ebx
 445:	ff c3                	inc    ebx
 447:	ff c3                	inc    ebx
 449:	ff c3                	inc    ebx
 44b:	ff c3                	inc    ebx
 44d:	ff c3                	inc    ebx
 44f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 452:	ff c3                	inc    ebx
 454:	ff c3                	inc    ebx
 456:	ff c3                	inc    ebx
 458:	ff c3                	inc    ebx
 45a:	ff c3                	inc    ebx
 45c:	ff c3                	inc    ebx
 45e:	ff c3                	inc    ebx
 460:	ff c3                	inc    ebx
 462:	ff c3                	inc    ebx
 464:	ff c3                	inc    ebx
 466:	ff c3                	inc    ebx
 468:	ff c3                	inc    ebx
 46a:	ff c3                	inc    ebx
 46c:	ff c3                	inc    ebx
 46e:	ff c3                	inc    ebx
 470:	ff c3                	inc    ebx
 472:	ff c3                	inc    ebx
 474:	ff c3                	inc    ebx
 476:	ff c3                	inc    ebx
 478:	ff c3                	inc    ebx
 47a:	ff c3                	inc    ebx
 47c:	ff c3                	inc    ebx
 47e:	ff c3                	inc    ebx
 480:	ff c3                	inc    ebx
 482:	ff c3                	inc    ebx
 484:	ff c3                	inc    ebx
 486:	ff c3                	inc    ebx
 488:	ff c3                	inc    ebx
 48a:	ff c3                	inc    ebx
 48c:	ff c3                	inc    ebx
 48e:	ff c3                	inc    ebx
 490:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 493:	ff c3                	inc    ebx
 495:	ff c3                	inc    ebx
 497:	ff c3                	inc    ebx
 499:	ff c3                	inc    ebx
 49b:	ff c3                	inc    ebx
 49d:	ff c3                	inc    ebx
 49f:	ff c3                	inc    ebx
 4a1:	ff c3                	inc    ebx
 4a3:	ff c3                	inc    ebx
 4a5:	ff c3                	inc    ebx
 4a7:	ff c3                	inc    ebx
 4a9:	ff c3                	inc    ebx
 4ab:	ff c3                	inc    ebx
 4ad:	ff c3                	inc    ebx
 4af:	ff c3                	inc    ebx
 4b1:	ff c3                	inc    ebx
 4b3:	ff c3                	inc    ebx
 4b5:	ff c3                	inc    ebx
 4b7:	ff c3                	inc    ebx
 4b9:	ff c3                	inc    ebx
 4bb:	ff c3                	inc    ebx
 4bd:	ff c3                	inc    ebx
 4bf:	ff c3                	inc    ebx
 4c1:	ff c3                	inc    ebx
 4c3:	ff c3                	inc    ebx
 4c5:	ff c3                	inc    ebx
 4c7:	ff c3                	inc    ebx
 4c9:	ff c3                	inc    ebx
 4cb:	ff c3                	inc    ebx
 4cd:	ff c3                	inc    ebx
 4cf:	ff c3                	inc    ebx
 4d1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 4d4:	ff c3                	inc    ebx
 4d6:	ff c3                	inc    ebx
 4d8:	ff c3                	inc    ebx
 4da:	ff c3                	inc    ebx
 4dc:	ff c3                	inc    ebx
 4de:	ff c3                	inc    ebx
 4e0:	ff c3                	inc    ebx
 4e2:	ff c3                	inc    ebx
 4e4:	ff c3                	inc    ebx
 4e6:	ff c3                	inc    ebx
 4e8:	ff c3                	inc    ebx
 4ea:	ff c3                	inc    ebx
 4ec:	ff c3                	inc    ebx
 4ee:	ff c3                	inc    ebx
 4f0:	ff c3                	inc    ebx
 4f2:	ff c3                	inc    ebx
 4f4:	ff c3                	inc    ebx
 4f6:	ff c3                	inc    ebx
 4f8:	ff c3                	inc    ebx
 4fa:	ff c3                	inc    ebx
 4fc:	ff c3                	inc    ebx
 4fe:	ff c3                	inc    ebx
 500:	ff c3                	inc    ebx
 502:	ff c3                	inc    ebx
 504:	ff c3                	inc    ebx
 506:	ff c3                	inc    ebx
 508:	ff c3                	inc    ebx
 50a:	ff c3                	inc    ebx
 50c:	ff c3                	inc    ebx
 50e:	ff c3                	inc    ebx
 510:	ff c3                	inc    ebx
 512:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 515:	ff c3                	inc    ebx
 517:	ff c3                	inc    ebx
 519:	ff c3                	inc    ebx
 51b:	ff c3                	inc    ebx
 51d:	ff c3                	inc    ebx
 51f:	ff c3                	inc    ebx
 521:	ff c3                	inc    ebx
 523:	ff c3                	inc    ebx
 525:	ff c3                	inc    ebx
 527:	ff c3                	inc    ebx
 529:	ff c3                	inc    ebx
 52b:	ff c3                	inc    ebx
 52d:	ff c3                	inc    ebx
 52f:	ff c3                	inc    ebx
 531:	ff c3                	inc    ebx
 533:	ff c3                	inc    ebx
 535:	ff c3                	inc    ebx
 537:	ff c3                	inc    ebx
 539:	ff c3                	inc    ebx
 53b:	ff c3                	inc    ebx
 53d:	ff c3                	inc    ebx
 53f:	ff c3                	inc    ebx
 541:	ff c3                	inc    ebx
 543:	ff c3                	inc    ebx
 545:	ff c3                	inc    ebx
 547:	ff c3                	inc    ebx
 549:	ff c3                	inc    ebx
 54b:	ff c3                	inc    ebx
 54d:	ff c3                	inc    ebx
 54f:	ff c3                	inc    ebx
 551:	ff c3                	inc    ebx
 553:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 556:	ff c3                	inc    ebx
 558:	ff c3                	inc    ebx
 55a:	ff c3                	inc    ebx
 55c:	ff c3                	inc    ebx
 55e:	ff c3                	inc    ebx
 560:	ff c3                	inc    ebx
 562:	ff c3                	inc    ebx
 564:	ff c3                	inc    ebx
 566:	ff c3                	inc    ebx
 568:	ff c3                	inc    ebx
 56a:	ff c3                	inc    ebx
 56c:	ff c3                	inc    ebx
 56e:	ff c3                	inc    ebx
 570:	ff c3                	inc    ebx
 572:	ff c3                	inc    ebx
 574:	ff c3                	inc    ebx
 576:	ff c3                	inc    ebx
 578:	ff c3                	inc    ebx
 57a:	ff c3                	inc    ebx
 57c:	ff c3                	inc    ebx
 57e:	ff c3                	inc    ebx
 580:	ff c3                	inc    ebx
 582:	ff c3                	inc    ebx
 584:	ff c3                	inc    ebx
 586:	ff c3                	inc    ebx
 588:	ff c3                	inc    ebx
 58a:	ff c3                	inc    ebx
 58c:	ff c3                	inc    ebx
 58e:	ff c3                	inc    ebx
 590:	ff c3                	inc    ebx
 592:	ff c3                	inc    ebx
 594:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 597:	ff c3                	inc    ebx
 599:	ff c3                	inc    ebx
 59b:	ff c3                	inc    ebx
 59d:	ff c3                	inc    ebx
 59f:	ff c3                	inc    ebx
 5a1:	ff c3                	inc    ebx
 5a3:	ff c3                	inc    ebx
 5a5:	ff c3                	inc    ebx
 5a7:	ff c3                	inc    ebx
 5a9:	ff c3                	inc    ebx
 5ab:	ff c3                	inc    ebx
 5ad:	ff c3                	inc    ebx
 5af:	ff c3                	inc    ebx
 5b1:	ff c3                	inc    ebx
 5b3:	ff c3                	inc    ebx
 5b5:	ff c3                	inc    ebx
 5b7:	ff c3                	inc    ebx
 5b9:	ff c3                	inc    ebx
 5bb:	ff c3                	inc    ebx
 5bd:	ff c3                	inc    ebx
 5bf:	ff c3                	inc    ebx
 5c1:	ff c3                	inc    ebx
 5c3:	ff c3                	inc    ebx
 5c5:	ff c3                	inc    ebx
 5c7:	ff c3                	inc    ebx
 5c9:	ff c3                	inc    ebx
 5cb:	ff c3                	inc    ebx
 5cd:	ff c3                	inc    ebx
 5cf:	ff c3                	inc    ebx
 5d1:	ff c3                	inc    ebx
 5d3:	ff c3                	inc    ebx
 5d5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 5d8:	ff c3                	inc    ebx
 5da:	ff c3                	inc    ebx
 5dc:	ff c3                	inc    ebx
 5de:	ff c3                	inc    ebx
 5e0:	ff c3                	inc    ebx
 5e2:	ff c3                	inc    ebx
 5e4:	ff c3                	inc    ebx
 5e6:	ff c3                	inc    ebx
 5e8:	ff c3                	inc    ebx
 5ea:	ff c3                	inc    ebx
 5ec:	ff c3                	inc    ebx
 5ee:	ff c3                	inc    ebx
 5f0:	ff c3                	inc    ebx
 5f2:	ff c3                	inc    ebx
 5f4:	ff c3                	inc    ebx
 5f6:	ff c3                	inc    ebx
 5f8:	ff c3                	inc    ebx
 5fa:	ff c3                	inc    ebx
 5fc:	ff c3                	inc    ebx
 5fe:	ff c3                	inc    ebx
 600:	ff c3                	inc    ebx
 602:	ff c3                	inc    ebx
 604:	ff c3                	inc    ebx
 606:	ff c3                	inc    ebx
 608:	ff c3                	inc    ebx
 60a:	ff c3                	inc    ebx
 60c:	ff c3                	inc    ebx
 60e:	ff c3                	inc    ebx
 610:	ff c3                	inc    ebx
 612:	ff c3                	inc    ebx
 614:	ff c3                	inc    ebx
 616:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 619:	ff c3                	inc    ebx
 61b:	ff c3                	inc    ebx
 61d:	ff c3                	inc    ebx
 61f:	ff c3                	inc    ebx
 621:	ff c3                	inc    ebx
 623:	ff c3                	inc    ebx
 625:	ff c3                	inc    ebx
 627:	ff c3                	inc    ebx
 629:	ff c3                	inc    ebx
 62b:	ff c3                	inc    ebx
 62d:	ff c3                	inc    ebx
 62f:	ff c3                	inc    ebx
 631:	ff c3                	inc    ebx
 633:	ff c3                	inc    ebx
 635:	ff c3                	inc    ebx
 637:	ff c3                	inc    ebx
 639:	ff c3                	inc    ebx
 63b:	ff c3                	inc    ebx
 63d:	ff c3                	inc    ebx
 63f:	ff c3                	inc    ebx
 641:	ff c3                	inc    ebx
 643:	ff c3                	inc    ebx
 645:	ff c3                	inc    ebx
 647:	ff c3                	inc    ebx
 649:	ff c3                	inc    ebx
 64b:	ff c3                	inc    ebx
 64d:	ff c3                	inc    ebx
 64f:	ff c3                	inc    ebx
 651:	ff c3                	inc    ebx
 653:	ff c3                	inc    ebx
 655:	ff c3                	inc    ebx
 657:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 65a:	ff c3                	inc    ebx
 65c:	ff c3                	inc    ebx
 65e:	ff c3                	inc    ebx
 660:	ff c3                	inc    ebx
 662:	ff c3                	inc    ebx
 664:	ff c3                	inc    ebx
 666:	ff c3                	inc    ebx
 668:	ff c3                	inc    ebx
 66a:	ff c3                	inc    ebx
 66c:	ff c3                	inc    ebx
 66e:	ff c3                	inc    ebx
 670:	ff c3                	inc    ebx
 672:	ff c3                	inc    ebx
 674:	ff c3                	inc    ebx
 676:	ff c3                	inc    ebx
 678:	ff c3                	inc    ebx
 67a:	ff c3                	inc    ebx
 67c:	ff c3                	inc    ebx
 67e:	ff c3                	inc    ebx
 680:	ff c3                	inc    ebx
 682:	ff c3                	inc    ebx
 684:	ff c3                	inc    ebx
 686:	ff c3                	inc    ebx
 688:	ff c3                	inc    ebx
 68a:	ff c3                	inc    ebx
 68c:	ff c3                	inc    ebx
 68e:	ff c3                	inc    ebx
 690:	ff c3                	inc    ebx
 692:	ff c3                	inc    ebx
 694:	ff c3                	inc    ebx
 696:	ff c3                	inc    ebx
 698:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 69b:	ff c3                	inc    ebx
 69d:	ff c3                	inc    ebx
 69f:	ff c3                	inc    ebx
 6a1:	ff c3                	inc    ebx
 6a3:	ff c3                	inc    ebx
 6a5:	ff c3                	inc    ebx
 6a7:	ff c3                	inc    ebx
 6a9:	ff c3                	inc    ebx
 6ab:	ff c3                	inc    ebx
 6ad:	ff c3                	inc    ebx
 6af:	ff c3                	inc    ebx
 6b1:	ff c3                	inc    ebx
 6b3:	ff c3                	inc    ebx
 6b5:	ff c3                	inc    ebx
 6b7:	ff c3                	inc    ebx
 6b9:	ff c3                	inc    ebx
 6bb:	ff c3                	inc    ebx
 6bd:	ff c3                	inc    ebx
 6bf:	ff c3                	inc    ebx
 6c1:	ff c3                	inc    ebx
 6c3:	ff c3                	inc    ebx
 6c5:	ff c3                	inc    ebx
 6c7:	ff c3                	inc    ebx
 6c9:	ff c3                	inc    ebx
 6cb:	ff c3                	inc    ebx
 6cd:	ff c3                	inc    ebx
 6cf:	ff c3                	inc    ebx
 6d1:	ff c3                	inc    ebx
 6d3:	ff c3                	inc    ebx
 6d5:	ff c3                	inc    ebx
 6d7:	ff c3                	inc    ebx
 6d9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 6dc:	ff c3                	inc    ebx
 6de:	ff c3                	inc    ebx
 6e0:	ff c3                	inc    ebx
 6e2:	ff c3                	inc    ebx
 6e4:	ff c3                	inc    ebx
 6e6:	ff c3                	inc    ebx
 6e8:	ff c3                	inc    ebx
 6ea:	ff c3                	inc    ebx
 6ec:	ff c3                	inc    ebx
 6ee:	ff c3                	inc    ebx
 6f0:	ff c3                	inc    ebx
 6f2:	ff c3                	inc    ebx
 6f4:	ff c3                	inc    ebx
 6f6:	ff c3                	inc    ebx
 6f8:	ff c3                	inc    ebx
 6fa:	ff c3                	inc    ebx
 6fc:	ff c3                	inc    ebx
 6fe:	ff c3                	inc    ebx
 700:	ff c3                	inc    ebx
 702:	ff c3                	inc    ebx
 704:	ff c3                	inc    ebx
 706:	ff c3                	inc    ebx
 708:	ff c3                	inc    ebx
 70a:	ff c3                	inc    ebx
 70c:	ff c3                	inc    ebx
 70e:	ff c3                	inc    ebx
 710:	ff c3                	inc    ebx
 712:	ff c3                	inc    ebx
 714:	ff c3                	inc    ebx
 716:	ff c3                	inc    ebx
 718:	ff c3                	inc    ebx
 71a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 71d:	ff c3                	inc    ebx
 71f:	ff c3                	inc    ebx
 721:	ff c3                	inc    ebx
 723:	ff c3                	inc    ebx
 725:	ff c3                	inc    ebx
 727:	ff c3                	inc    ebx
 729:	ff c3                	inc    ebx
 72b:	ff c3                	inc    ebx
 72d:	ff c3                	inc    ebx
 72f:	ff c3                	inc    ebx
 731:	ff c3                	inc    ebx
 733:	ff c3                	inc    ebx
 735:	ff c3                	inc    ebx
 737:	ff c3                	inc    ebx
 739:	ff c3                	inc    ebx
 73b:	ff c3                	inc    ebx
 73d:	ff c3                	inc    ebx
 73f:	ff c3                	inc    ebx
 741:	ff c3                	inc    ebx
 743:	ff c3                	inc    ebx
 745:	ff c3                	inc    ebx
 747:	ff c3                	inc    ebx
 749:	ff c3                	inc    ebx
 74b:	ff c3                	inc    ebx
 74d:	ff c3                	inc    ebx
 74f:	ff c3                	inc    ebx
 751:	ff c3                	inc    ebx
 753:	ff c3                	inc    ebx
 755:	ff c3                	inc    ebx
 757:	ff c3                	inc    ebx
 759:	ff c3                	inc    ebx
 75b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 75e:	ff c3                	inc    ebx
 760:	ff c3                	inc    ebx
 762:	ff c3                	inc    ebx
 764:	ff c3                	inc    ebx
 766:	ff c3                	inc    ebx
 768:	ff c3                	inc    ebx
 76a:	ff c3                	inc    ebx
 76c:	ff c3                	inc    ebx
 76e:	ff c3                	inc    ebx
 770:	ff c3                	inc    ebx
 772:	ff c3                	inc    ebx
 774:	ff c3                	inc    ebx
 776:	ff c3                	inc    ebx
 778:	ff c3                	inc    ebx
 77a:	ff c3                	inc    ebx
 77c:	ff c3                	inc    ebx
 77e:	ff c3                	inc    ebx
 780:	ff c3                	inc    ebx
 782:	ff c3                	inc    ebx
 784:	ff c3                	inc    ebx
 786:	ff c3                	inc    ebx
 788:	ff c3                	inc    ebx
 78a:	ff c3                	inc    ebx
 78c:	ff c3                	inc    ebx
 78e:	ff c3                	inc    ebx
 790:	ff c3                	inc    ebx
 792:	ff c3                	inc    ebx
 794:	ff c3                	inc    ebx
 796:	ff c3                	inc    ebx
 798:	ff c3                	inc    ebx
 79a:	ff c3                	inc    ebx
 79c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 79f:	ff c3                	inc    ebx
 7a1:	ff c3                	inc    ebx
 7a3:	ff c3                	inc    ebx
 7a5:	ff c3                	inc    ebx
 7a7:	ff c3                	inc    ebx
 7a9:	ff c3                	inc    ebx
 7ab:	ff c3                	inc    ebx
 7ad:	ff c3                	inc    ebx
 7af:	ff c3                	inc    ebx
 7b1:	ff c3                	inc    ebx
 7b3:	ff c3                	inc    ebx
 7b5:	ff c3                	inc    ebx
 7b7:	ff c3                	inc    ebx
 7b9:	ff c3                	inc    ebx
 7bb:	ff c3                	inc    ebx
 7bd:	ff c3                	inc    ebx
 7bf:	ff c3                	inc    ebx
 7c1:	ff c3                	inc    ebx
 7c3:	ff c3                	inc    ebx
 7c5:	ff c3                	inc    ebx
 7c7:	ff c3                	inc    ebx
 7c9:	ff c3                	inc    ebx
 7cb:	ff c3                	inc    ebx
 7cd:	ff c3                	inc    ebx
 7cf:	ff c3                	inc    ebx
 7d1:	ff c3                	inc    ebx
 7d3:	ff c3                	inc    ebx
 7d5:	ff c3                	inc    ebx
 7d7:	ff c3                	inc    ebx
 7d9:	ff c3                	inc    ebx
 7db:	ff c3                	inc    ebx
 7dd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 7e0:	ff c3                	inc    ebx
 7e2:	ff c3                	inc    ebx
 7e4:	ff c3                	inc    ebx
 7e6:	ff c3                	inc    ebx
 7e8:	ff c3                	inc    ebx
 7ea:	ff c3                	inc    ebx
 7ec:	ff c3                	inc    ebx
 7ee:	ff c3                	inc    ebx
 7f0:	ff c3                	inc    ebx
 7f2:	ff c3                	inc    ebx
 7f4:	ff c3                	inc    ebx
 7f6:	ff c3                	inc    ebx
 7f8:	ff c3                	inc    ebx
 7fa:	ff c3                	inc    ebx
 7fc:	ff c3                	inc    ebx
 7fe:	ff c3                	inc    ebx
 800:	ff c3                	inc    ebx
 802:	ff c3                	inc    ebx
 804:	ff c3                	inc    ebx
 806:	ff c3                	inc    ebx
 808:	ff c3                	inc    ebx
 80a:	ff c3                	inc    ebx
 80c:	ff c3                	inc    ebx
 80e:	ff c3                	inc    ebx
 810:	ff c3                	inc    ebx
 812:	ff c3                	inc    ebx
 814:	ff c3                	inc    ebx
 816:	ff c3                	inc    ebx
 818:	ff c3                	inc    ebx
 81a:	ff c3                	inc    ebx
 81c:	ff c3                	inc    ebx
 81e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 821:	ff c3                	inc    ebx
 823:	ff c3                	inc    ebx
 825:	ff c3                	inc    ebx
 827:	ff c3                	inc    ebx
 829:	ff c3                	inc    ebx
 82b:	ff c3                	inc    ebx
 82d:	ff c3                	inc    ebx
 82f:	ff c3                	inc    ebx
 831:	ff c3                	inc    ebx
 833:	ff c3                	inc    ebx
 835:	ff c3                	inc    ebx
 837:	ff c3                	inc    ebx
 839:	ff c3                	inc    ebx
 83b:	ff c3                	inc    ebx
 83d:	ff c3                	inc    ebx
 83f:	ff c3                	inc    ebx
 841:	ff c3                	inc    ebx
 843:	ff c3                	inc    ebx
 845:	ff c3                	inc    ebx
 847:	ff c3                	inc    ebx
 849:	ff c3                	inc    ebx
 84b:	ff c3                	inc    ebx
 84d:	ff c3                	inc    ebx
 84f:	ff c3                	inc    ebx
 851:	ff c3                	inc    ebx
 853:	ff c3                	inc    ebx
 855:	ff c3                	inc    ebx
 857:	ff c3                	inc    ebx
 859:	ff c3                	inc    ebx
 85b:	ff c3                	inc    ebx
 85d:	ff c3                	inc    ebx
 85f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 862:	ff c3                	inc    ebx
 864:	ff c3                	inc    ebx
 866:	ff c3                	inc    ebx
 868:	ff c3                	inc    ebx
 86a:	ff c3                	inc    ebx
 86c:	ff c3                	inc    ebx
 86e:	ff c3                	inc    ebx
 870:	ff c3                	inc    ebx
 872:	ff c3                	inc    ebx
 874:	ff c3                	inc    ebx
 876:	ff c3                	inc    ebx
 878:	ff c3                	inc    ebx
 87a:	ff c3                	inc    ebx
 87c:	ff c3                	inc    ebx
 87e:	ff c3                	inc    ebx
 880:	ff c3                	inc    ebx
 882:	ff c3                	inc    ebx
 884:	ff c3                	inc    ebx
 886:	ff c3                	inc    ebx
 888:	ff c3                	inc    ebx
 88a:	ff c3                	inc    ebx
 88c:	ff c3                	inc    ebx
 88e:	ff c3                	inc    ebx
 890:	ff c3                	inc    ebx
 892:	ff c3                	inc    ebx
 894:	ff c3                	inc    ebx
 896:	ff c3                	inc    ebx
 898:	ff c3                	inc    ebx
 89a:	ff c3                	inc    ebx
 89c:	ff c3                	inc    ebx
 89e:	ff c3                	inc    ebx
 8a0:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 8a3:	ff c3                	inc    ebx
 8a5:	ff c3                	inc    ebx
 8a7:	ff c3                	inc    ebx
 8a9:	ff c3                	inc    ebx
 8ab:	ff c3                	inc    ebx
 8ad:	ff c3                	inc    ebx
 8af:	ff c3                	inc    ebx
 8b1:	ff c3                	inc    ebx
 8b3:	ff c3                	inc    ebx
 8b5:	ff c3                	inc    ebx
 8b7:	ff c3                	inc    ebx
 8b9:	ff c3                	inc    ebx
 8bb:	ff c3                	inc    ebx
 8bd:	ff c3                	inc    ebx
 8bf:	ff c3                	inc    ebx
 8c1:	ff c3                	inc    ebx
 8c3:	ff c3                	inc    ebx
 8c5:	ff c3                	inc    ebx
 8c7:	ff c3                	inc    ebx
 8c9:	ff c3                	inc    ebx
 8cb:	ff c3                	inc    ebx
 8cd:	ff c3                	inc    ebx
 8cf:	ff c3                	inc    ebx
 8d1:	ff c3                	inc    ebx
 8d3:	ff c3                	inc    ebx
 8d5:	ff c3                	inc    ebx
 8d7:	ff c3                	inc    ebx
 8d9:	ff c3                	inc    ebx
 8db:	ff c3                	inc    ebx
 8dd:	ff c3                	inc    ebx
 8df:	ff c3                	inc    ebx
 8e1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 8e4:	ff c3                	inc    ebx
 8e6:	ff c3                	inc    ebx
 8e8:	ff c3                	inc    ebx
 8ea:	ff c3                	inc    ebx
 8ec:	ff c3                	inc    ebx
 8ee:	ff c3                	inc    ebx
 8f0:	ff c3                	inc    ebx
 8f2:	ff c3                	inc    ebx
 8f4:	ff c3                	inc    ebx
 8f6:	ff c3                	inc    ebx
 8f8:	ff c3                	inc    ebx
 8fa:	ff c3                	inc    ebx
 8fc:	ff c3                	inc    ebx
 8fe:	ff c3                	inc    ebx
 900:	ff c3                	inc    ebx
 902:	ff c3                	inc    ebx
 904:	ff c3                	inc    ebx
 906:	ff c3                	inc    ebx
 908:	ff c3                	inc    ebx
 90a:	ff c3                	inc    ebx
 90c:	ff c3                	inc    ebx
 90e:	ff c3                	inc    ebx
 910:	ff c3                	inc    ebx
 912:	ff c3                	inc    ebx
 914:	ff c3                	inc    ebx
 916:	ff c3                	inc    ebx
 918:	ff c3                	inc    ebx
 91a:	ff c3                	inc    ebx
 91c:	ff c3                	inc    ebx
 91e:	ff c3                	inc    ebx
 920:	ff c3                	inc    ebx
 922:	83 e8 01             	sub    eax,0x1
 925:	0f 85 55 f7 ff ff    	jne    0x80
 92b:	66 90                	xchg   ax,ax
 92d:	66 90                	xchg   ax,ax
 92f:	66 90                	xchg   ax,ax
 931:	66 90                	xchg   ax,ax
 933:	66 90                	xchg   ax,ax
 935:	66 90                	xchg   ax,ax
 937:	66 90                	xchg   ax,ax
 939:	66 90                	xchg   ax,ax
 93b:	48 81 c4 a4 6a 00 00 	add    rsp,0x6aa4
 942:	41 59                	pop    r9
 944:	41 58                	pop    r8
 946:	5f                   	pop    rdi
 947:	5e                   	pop    rsi
 948:	5d                   	pop    rbp
 949:	5b                   	pop    rbx
 94a:	0f 77                	emms   
 94c:	c3                   	ret    
