
asm.bin:     file format binary


Disassembly of section .data:

0000000000000000 <.data>:
   0:	66 90                	xchg   ax,ax
   2:	66 90                	xchg   ax,ax
   4:	66 90                	xchg   ax,ax
   6:	66 90                	xchg   ax,ax
   8:	66 90                	xchg   ax,ax
   a:	66 90                	xchg   ax,ax
   c:	66 90                	xchg   ax,ax
   e:	66 90                	xchg   ax,ax
  10:	53                   	push   rbx
  11:	55                   	push   rbp
  12:	56                   	push   rsi
  13:	57                   	push   rdi
  14:	41 50                	push   r8
  16:	41 51                	push   r9
  18:	48 81 ec a4 6a 00 00 	sub    rsp,0x6aa4
  1f:	45 31 c0             	xor    r8d,r8d
  22:	4c 8d 0c 24          	lea    r9,[rsp]
  26:	48 b9 01 00 00 00 00 	movabs rcx,0x1
  2d:	00 00 00 
  30:	48 ba 02 00 00 00 00 	movabs rdx,0x2
  37:	00 00 00 
  3a:	48 b8 00 20 00 00 00 	movabs rax,0x2000
  41:	00 00 00 
  44:	48 83 eb 00          	sub    rbx,0x0
  48:	48 83 ed 00          	sub    rbp,0x0
  4c:	48 83 ee 00          	sub    rsi,0x0
  50:	48 83 ef 00          	sub    rdi,0x0
  54:	49 83 e8 00          	sub    r8,0x0
  58:	49 83 e9 00          	sub    r9,0x0
  5c:	49 83 ea 00          	sub    r10,0x0
  60:	49 83 eb 00          	sub    r11,0x0
  64:	49 83 ec 00          	sub    r12,0x0
  68:	49 83 ed 00          	sub    r13,0x0
  6c:	49 83 ee 00          	sub    r14,0x0
  70:	49 83 ef 00          	sub    r15,0x0
  74:	90                   	nop
  75:	90                   	nop
  76:	90                   	nop
  77:	90                   	nop
  78:	90                   	nop
  79:	90                   	nop
  7a:	90                   	nop
  7b:	90                   	nop
  7c:	90                   	nop
  7d:	90                   	nop
  7e:	90                   	nop
  7f:	90                   	nop
  80:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
  83:	fe c3                	inc    bl
  85:	fe c3                	inc    bl
  87:	fe c3                	inc    bl
  89:	fe c3                	inc    bl
  8b:	fe c3                	inc    bl
  8d:	fe c3                	inc    bl
  8f:	fe c3                	inc    bl
  91:	fe c3                	inc    bl
  93:	fe c3                	inc    bl
  95:	fe c3                	inc    bl
  97:	fe c3                	inc    bl
  99:	fe c3                	inc    bl
  9b:	fe c3                	inc    bl
  9d:	fe c3                	inc    bl
  9f:	fe c3                	inc    bl
  a1:	fe c3                	inc    bl
  a3:	fe c3                	inc    bl
  a5:	fe c3                	inc    bl
  a7:	fe c3                	inc    bl
  a9:	fe c3                	inc    bl
  ab:	fe c3                	inc    bl
  ad:	fe c3                	inc    bl
  af:	fe c3                	inc    bl
  b1:	fe c3                	inc    bl
  b3:	fe c3                	inc    bl
  b5:	fe c3                	inc    bl
  b7:	fe c3                	inc    bl
  b9:	fe c3                	inc    bl
  bb:	fe c3                	inc    bl
  bd:	fe c3                	inc    bl
  bf:	fe c3                	inc    bl
  c1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
  c4:	fe c3                	inc    bl
  c6:	fe c3                	inc    bl
  c8:	fe c3                	inc    bl
  ca:	fe c3                	inc    bl
  cc:	fe c3                	inc    bl
  ce:	fe c3                	inc    bl
  d0:	fe c3                	inc    bl
  d2:	fe c3                	inc    bl
  d4:	fe c3                	inc    bl
  d6:	fe c3                	inc    bl
  d8:	fe c3                	inc    bl
  da:	fe c3                	inc    bl
  dc:	fe c3                	inc    bl
  de:	fe c3                	inc    bl
  e0:	fe c3                	inc    bl
  e2:	fe c3                	inc    bl
  e4:	fe c3                	inc    bl
  e6:	fe c3                	inc    bl
  e8:	fe c3                	inc    bl
  ea:	fe c3                	inc    bl
  ec:	fe c3                	inc    bl
  ee:	fe c3                	inc    bl
  f0:	fe c3                	inc    bl
  f2:	fe c3                	inc    bl
  f4:	fe c3                	inc    bl
  f6:	fe c3                	inc    bl
  f8:	fe c3                	inc    bl
  fa:	fe c3                	inc    bl
  fc:	fe c3                	inc    bl
  fe:	fe c3                	inc    bl
 100:	fe c3                	inc    bl
 102:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 105:	fe c3                	inc    bl
 107:	fe c3                	inc    bl
 109:	fe c3                	inc    bl
 10b:	fe c3                	inc    bl
 10d:	fe c3                	inc    bl
 10f:	fe c3                	inc    bl
 111:	fe c3                	inc    bl
 113:	fe c3                	inc    bl
 115:	fe c3                	inc    bl
 117:	fe c3                	inc    bl
 119:	fe c3                	inc    bl
 11b:	fe c3                	inc    bl
 11d:	fe c3                	inc    bl
 11f:	fe c3                	inc    bl
 121:	fe c3                	inc    bl
 123:	fe c3                	inc    bl
 125:	fe c3                	inc    bl
 127:	fe c3                	inc    bl
 129:	fe c3                	inc    bl
 12b:	fe c3                	inc    bl
 12d:	fe c3                	inc    bl
 12f:	fe c3                	inc    bl
 131:	fe c3                	inc    bl
 133:	fe c3                	inc    bl
 135:	fe c3                	inc    bl
 137:	fe c3                	inc    bl
 139:	fe c3                	inc    bl
 13b:	fe c3                	inc    bl
 13d:	fe c3                	inc    bl
 13f:	fe c3                	inc    bl
 141:	fe c3                	inc    bl
 143:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 146:	fe c3                	inc    bl
 148:	fe c3                	inc    bl
 14a:	fe c3                	inc    bl
 14c:	fe c3                	inc    bl
 14e:	fe c3                	inc    bl
 150:	fe c3                	inc    bl
 152:	fe c3                	inc    bl
 154:	fe c3                	inc    bl
 156:	fe c3                	inc    bl
 158:	fe c3                	inc    bl
 15a:	fe c3                	inc    bl
 15c:	fe c3                	inc    bl
 15e:	fe c3                	inc    bl
 160:	fe c3                	inc    bl
 162:	fe c3                	inc    bl
 164:	fe c3                	inc    bl
 166:	fe c3                	inc    bl
 168:	fe c3                	inc    bl
 16a:	fe c3                	inc    bl
 16c:	fe c3                	inc    bl
 16e:	fe c3                	inc    bl
 170:	fe c3                	inc    bl
 172:	fe c3                	inc    bl
 174:	fe c3                	inc    bl
 176:	fe c3                	inc    bl
 178:	fe c3                	inc    bl
 17a:	fe c3                	inc    bl
 17c:	fe c3                	inc    bl
 17e:	fe c3                	inc    bl
 180:	fe c3                	inc    bl
 182:	fe c3                	inc    bl
 184:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 187:	fe c3                	inc    bl
 189:	fe c3                	inc    bl
 18b:	fe c3                	inc    bl
 18d:	fe c3                	inc    bl
 18f:	fe c3                	inc    bl
 191:	fe c3                	inc    bl
 193:	fe c3                	inc    bl
 195:	fe c3                	inc    bl
 197:	fe c3                	inc    bl
 199:	fe c3                	inc    bl
 19b:	fe c3                	inc    bl
 19d:	fe c3                	inc    bl
 19f:	fe c3                	inc    bl
 1a1:	fe c3                	inc    bl
 1a3:	fe c3                	inc    bl
 1a5:	fe c3                	inc    bl
 1a7:	fe c3                	inc    bl
 1a9:	fe c3                	inc    bl
 1ab:	fe c3                	inc    bl
 1ad:	fe c3                	inc    bl
 1af:	fe c3                	inc    bl
 1b1:	fe c3                	inc    bl
 1b3:	fe c3                	inc    bl
 1b5:	fe c3                	inc    bl
 1b7:	fe c3                	inc    bl
 1b9:	fe c3                	inc    bl
 1bb:	fe c3                	inc    bl
 1bd:	fe c3                	inc    bl
 1bf:	fe c3                	inc    bl
 1c1:	fe c3                	inc    bl
 1c3:	fe c3                	inc    bl
 1c5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 1c8:	fe c3                	inc    bl
 1ca:	fe c3                	inc    bl
 1cc:	fe c3                	inc    bl
 1ce:	fe c3                	inc    bl
 1d0:	fe c3                	inc    bl
 1d2:	fe c3                	inc    bl
 1d4:	fe c3                	inc    bl
 1d6:	fe c3                	inc    bl
 1d8:	fe c3                	inc    bl
 1da:	fe c3                	inc    bl
 1dc:	fe c3                	inc    bl
 1de:	fe c3                	inc    bl
 1e0:	fe c3                	inc    bl
 1e2:	fe c3                	inc    bl
 1e4:	fe c3                	inc    bl
 1e6:	fe c3                	inc    bl
 1e8:	fe c3                	inc    bl
 1ea:	fe c3                	inc    bl
 1ec:	fe c3                	inc    bl
 1ee:	fe c3                	inc    bl
 1f0:	fe c3                	inc    bl
 1f2:	fe c3                	inc    bl
 1f4:	fe c3                	inc    bl
 1f6:	fe c3                	inc    bl
 1f8:	fe c3                	inc    bl
 1fa:	fe c3                	inc    bl
 1fc:	fe c3                	inc    bl
 1fe:	fe c3                	inc    bl
 200:	fe c3                	inc    bl
 202:	fe c3                	inc    bl
 204:	fe c3                	inc    bl
 206:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 209:	fe c3                	inc    bl
 20b:	fe c3                	inc    bl
 20d:	fe c3                	inc    bl
 20f:	fe c3                	inc    bl
 211:	fe c3                	inc    bl
 213:	fe c3                	inc    bl
 215:	fe c3                	inc    bl
 217:	fe c3                	inc    bl
 219:	fe c3                	inc    bl
 21b:	fe c3                	inc    bl
 21d:	fe c3                	inc    bl
 21f:	fe c3                	inc    bl
 221:	fe c3                	inc    bl
 223:	fe c3                	inc    bl
 225:	fe c3                	inc    bl
 227:	fe c3                	inc    bl
 229:	fe c3                	inc    bl
 22b:	fe c3                	inc    bl
 22d:	fe c3                	inc    bl
 22f:	fe c3                	inc    bl
 231:	fe c3                	inc    bl
 233:	fe c3                	inc    bl
 235:	fe c3                	inc    bl
 237:	fe c3                	inc    bl
 239:	fe c3                	inc    bl
 23b:	fe c3                	inc    bl
 23d:	fe c3                	inc    bl
 23f:	fe c3                	inc    bl
 241:	fe c3                	inc    bl
 243:	fe c3                	inc    bl
 245:	fe c3                	inc    bl
 247:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 24a:	fe c3                	inc    bl
 24c:	fe c3                	inc    bl
 24e:	fe c3                	inc    bl
 250:	fe c3                	inc    bl
 252:	fe c3                	inc    bl
 254:	fe c3                	inc    bl
 256:	fe c3                	inc    bl
 258:	fe c3                	inc    bl
 25a:	fe c3                	inc    bl
 25c:	fe c3                	inc    bl
 25e:	fe c3                	inc    bl
 260:	fe c3                	inc    bl
 262:	fe c3                	inc    bl
 264:	fe c3                	inc    bl
 266:	fe c3                	inc    bl
 268:	fe c3                	inc    bl
 26a:	fe c3                	inc    bl
 26c:	fe c3                	inc    bl
 26e:	fe c3                	inc    bl
 270:	fe c3                	inc    bl
 272:	fe c3                	inc    bl
 274:	fe c3                	inc    bl
 276:	fe c3                	inc    bl
 278:	fe c3                	inc    bl
 27a:	fe c3                	inc    bl
 27c:	fe c3                	inc    bl
 27e:	fe c3                	inc    bl
 280:	fe c3                	inc    bl
 282:	fe c3                	inc    bl
 284:	fe c3                	inc    bl
 286:	fe c3                	inc    bl
 288:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 28b:	fe c3                	inc    bl
 28d:	fe c3                	inc    bl
 28f:	fe c3                	inc    bl
 291:	fe c3                	inc    bl
 293:	fe c3                	inc    bl
 295:	fe c3                	inc    bl
 297:	fe c3                	inc    bl
 299:	fe c3                	inc    bl
 29b:	fe c3                	inc    bl
 29d:	fe c3                	inc    bl
 29f:	fe c3                	inc    bl
 2a1:	fe c3                	inc    bl
 2a3:	fe c3                	inc    bl
 2a5:	fe c3                	inc    bl
 2a7:	fe c3                	inc    bl
 2a9:	fe c3                	inc    bl
 2ab:	fe c3                	inc    bl
 2ad:	fe c3                	inc    bl
 2af:	fe c3                	inc    bl
 2b1:	fe c3                	inc    bl
 2b3:	fe c3                	inc    bl
 2b5:	fe c3                	inc    bl
 2b7:	fe c3                	inc    bl
 2b9:	fe c3                	inc    bl
 2bb:	fe c3                	inc    bl
 2bd:	fe c3                	inc    bl
 2bf:	fe c3                	inc    bl
 2c1:	fe c3                	inc    bl
 2c3:	fe c3                	inc    bl
 2c5:	fe c3                	inc    bl
 2c7:	fe c3                	inc    bl
 2c9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 2cc:	fe c3                	inc    bl
 2ce:	fe c3                	inc    bl
 2d0:	fe c3                	inc    bl
 2d2:	fe c3                	inc    bl
 2d4:	fe c3                	inc    bl
 2d6:	fe c3                	inc    bl
 2d8:	fe c3                	inc    bl
 2da:	fe c3                	inc    bl
 2dc:	fe c3                	inc    bl
 2de:	fe c3                	inc    bl
 2e0:	fe c3                	inc    bl
 2e2:	fe c3                	inc    bl
 2e4:	fe c3                	inc    bl
 2e6:	fe c3                	inc    bl
 2e8:	fe c3                	inc    bl
 2ea:	fe c3                	inc    bl
 2ec:	fe c3                	inc    bl
 2ee:	fe c3                	inc    bl
 2f0:	fe c3                	inc    bl
 2f2:	fe c3                	inc    bl
 2f4:	fe c3                	inc    bl
 2f6:	fe c3                	inc    bl
 2f8:	fe c3                	inc    bl
 2fa:	fe c3                	inc    bl
 2fc:	fe c3                	inc    bl
 2fe:	fe c3                	inc    bl
 300:	fe c3                	inc    bl
 302:	fe c3                	inc    bl
 304:	fe c3                	inc    bl
 306:	fe c3                	inc    bl
 308:	fe c3                	inc    bl
 30a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 30d:	fe c3                	inc    bl
 30f:	fe c3                	inc    bl
 311:	fe c3                	inc    bl
 313:	fe c3                	inc    bl
 315:	fe c3                	inc    bl
 317:	fe c3                	inc    bl
 319:	fe c3                	inc    bl
 31b:	fe c3                	inc    bl
 31d:	fe c3                	inc    bl
 31f:	fe c3                	inc    bl
 321:	fe c3                	inc    bl
 323:	fe c3                	inc    bl
 325:	fe c3                	inc    bl
 327:	fe c3                	inc    bl
 329:	fe c3                	inc    bl
 32b:	fe c3                	inc    bl
 32d:	fe c3                	inc    bl
 32f:	fe c3                	inc    bl
 331:	fe c3                	inc    bl
 333:	fe c3                	inc    bl
 335:	fe c3                	inc    bl
 337:	fe c3                	inc    bl
 339:	fe c3                	inc    bl
 33b:	fe c3                	inc    bl
 33d:	fe c3                	inc    bl
 33f:	fe c3                	inc    bl
 341:	fe c3                	inc    bl
 343:	fe c3                	inc    bl
 345:	fe c3                	inc    bl
 347:	fe c3                	inc    bl
 349:	fe c3                	inc    bl
 34b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 34e:	fe c3                	inc    bl
 350:	fe c3                	inc    bl
 352:	fe c3                	inc    bl
 354:	fe c3                	inc    bl
 356:	fe c3                	inc    bl
 358:	fe c3                	inc    bl
 35a:	fe c3                	inc    bl
 35c:	fe c3                	inc    bl
 35e:	fe c3                	inc    bl
 360:	fe c3                	inc    bl
 362:	fe c3                	inc    bl
 364:	fe c3                	inc    bl
 366:	fe c3                	inc    bl
 368:	fe c3                	inc    bl
 36a:	fe c3                	inc    bl
 36c:	fe c3                	inc    bl
 36e:	fe c3                	inc    bl
 370:	fe c3                	inc    bl
 372:	fe c3                	inc    bl
 374:	fe c3                	inc    bl
 376:	fe c3                	inc    bl
 378:	fe c3                	inc    bl
 37a:	fe c3                	inc    bl
 37c:	fe c3                	inc    bl
 37e:	fe c3                	inc    bl
 380:	fe c3                	inc    bl
 382:	fe c3                	inc    bl
 384:	fe c3                	inc    bl
 386:	fe c3                	inc    bl
 388:	fe c3                	inc    bl
 38a:	fe c3                	inc    bl
 38c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 38f:	fe c3                	inc    bl
 391:	fe c3                	inc    bl
 393:	fe c3                	inc    bl
 395:	fe c3                	inc    bl
 397:	fe c3                	inc    bl
 399:	fe c3                	inc    bl
 39b:	fe c3                	inc    bl
 39d:	fe c3                	inc    bl
 39f:	fe c3                	inc    bl
 3a1:	fe c3                	inc    bl
 3a3:	fe c3                	inc    bl
 3a5:	fe c3                	inc    bl
 3a7:	fe c3                	inc    bl
 3a9:	fe c3                	inc    bl
 3ab:	fe c3                	inc    bl
 3ad:	fe c3                	inc    bl
 3af:	fe c3                	inc    bl
 3b1:	fe c3                	inc    bl
 3b3:	fe c3                	inc    bl
 3b5:	fe c3                	inc    bl
 3b7:	fe c3                	inc    bl
 3b9:	fe c3                	inc    bl
 3bb:	fe c3                	inc    bl
 3bd:	fe c3                	inc    bl
 3bf:	fe c3                	inc    bl
 3c1:	fe c3                	inc    bl
 3c3:	fe c3                	inc    bl
 3c5:	fe c3                	inc    bl
 3c7:	fe c3                	inc    bl
 3c9:	fe c3                	inc    bl
 3cb:	fe c3                	inc    bl
 3cd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 3d0:	fe c3                	inc    bl
 3d2:	fe c3                	inc    bl
 3d4:	fe c3                	inc    bl
 3d6:	fe c3                	inc    bl
 3d8:	fe c3                	inc    bl
 3da:	fe c3                	inc    bl
 3dc:	fe c3                	inc    bl
 3de:	fe c3                	inc    bl
 3e0:	fe c3                	inc    bl
 3e2:	fe c3                	inc    bl
 3e4:	fe c3                	inc    bl
 3e6:	fe c3                	inc    bl
 3e8:	fe c3                	inc    bl
 3ea:	fe c3                	inc    bl
 3ec:	fe c3                	inc    bl
 3ee:	fe c3                	inc    bl
 3f0:	fe c3                	inc    bl
 3f2:	fe c3                	inc    bl
 3f4:	fe c3                	inc    bl
 3f6:	fe c3                	inc    bl
 3f8:	fe c3                	inc    bl
 3fa:	fe c3                	inc    bl
 3fc:	fe c3                	inc    bl
 3fe:	fe c3                	inc    bl
 400:	fe c3                	inc    bl
 402:	fe c3                	inc    bl
 404:	fe c3                	inc    bl
 406:	fe c3                	inc    bl
 408:	fe c3                	inc    bl
 40a:	fe c3                	inc    bl
 40c:	fe c3                	inc    bl
 40e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 411:	fe c3                	inc    bl
 413:	fe c3                	inc    bl
 415:	fe c3                	inc    bl
 417:	fe c3                	inc    bl
 419:	fe c3                	inc    bl
 41b:	fe c3                	inc    bl
 41d:	fe c3                	inc    bl
 41f:	fe c3                	inc    bl
 421:	fe c3                	inc    bl
 423:	fe c3                	inc    bl
 425:	fe c3                	inc    bl
 427:	fe c3                	inc    bl
 429:	fe c3                	inc    bl
 42b:	fe c3                	inc    bl
 42d:	fe c3                	inc    bl
 42f:	fe c3                	inc    bl
 431:	fe c3                	inc    bl
 433:	fe c3                	inc    bl
 435:	fe c3                	inc    bl
 437:	fe c3                	inc    bl
 439:	fe c3                	inc    bl
 43b:	fe c3                	inc    bl
 43d:	fe c3                	inc    bl
 43f:	fe c3                	inc    bl
 441:	fe c3                	inc    bl
 443:	fe c3                	inc    bl
 445:	fe c3                	inc    bl
 447:	fe c3                	inc    bl
 449:	fe c3                	inc    bl
 44b:	fe c3                	inc    bl
 44d:	fe c3                	inc    bl
 44f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 452:	fe c3                	inc    bl
 454:	fe c3                	inc    bl
 456:	fe c3                	inc    bl
 458:	fe c3                	inc    bl
 45a:	fe c3                	inc    bl
 45c:	fe c3                	inc    bl
 45e:	fe c3                	inc    bl
 460:	fe c3                	inc    bl
 462:	fe c3                	inc    bl
 464:	fe c3                	inc    bl
 466:	fe c3                	inc    bl
 468:	fe c3                	inc    bl
 46a:	fe c3                	inc    bl
 46c:	fe c3                	inc    bl
 46e:	fe c3                	inc    bl
 470:	fe c3                	inc    bl
 472:	fe c3                	inc    bl
 474:	fe c3                	inc    bl
 476:	fe c3                	inc    bl
 478:	fe c3                	inc    bl
 47a:	fe c3                	inc    bl
 47c:	fe c3                	inc    bl
 47e:	fe c3                	inc    bl
 480:	fe c3                	inc    bl
 482:	fe c3                	inc    bl
 484:	fe c3                	inc    bl
 486:	fe c3                	inc    bl
 488:	fe c3                	inc    bl
 48a:	fe c3                	inc    bl
 48c:	fe c3                	inc    bl
 48e:	fe c3                	inc    bl
 490:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 493:	fe c3                	inc    bl
 495:	fe c3                	inc    bl
 497:	fe c3                	inc    bl
 499:	fe c3                	inc    bl
 49b:	fe c3                	inc    bl
 49d:	fe c3                	inc    bl
 49f:	fe c3                	inc    bl
 4a1:	fe c3                	inc    bl
 4a3:	fe c3                	inc    bl
 4a5:	fe c3                	inc    bl
 4a7:	fe c3                	inc    bl
 4a9:	fe c3                	inc    bl
 4ab:	fe c3                	inc    bl
 4ad:	fe c3                	inc    bl
 4af:	fe c3                	inc    bl
 4b1:	fe c3                	inc    bl
 4b3:	fe c3                	inc    bl
 4b5:	fe c3                	inc    bl
 4b7:	fe c3                	inc    bl
 4b9:	fe c3                	inc    bl
 4bb:	fe c3                	inc    bl
 4bd:	fe c3                	inc    bl
 4bf:	fe c3                	inc    bl
 4c1:	fe c3                	inc    bl
 4c3:	fe c3                	inc    bl
 4c5:	fe c3                	inc    bl
 4c7:	fe c3                	inc    bl
 4c9:	fe c3                	inc    bl
 4cb:	fe c3                	inc    bl
 4cd:	fe c3                	inc    bl
 4cf:	fe c3                	inc    bl
 4d1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 4d4:	fe c3                	inc    bl
 4d6:	fe c3                	inc    bl
 4d8:	fe c3                	inc    bl
 4da:	fe c3                	inc    bl
 4dc:	fe c3                	inc    bl
 4de:	fe c3                	inc    bl
 4e0:	fe c3                	inc    bl
 4e2:	fe c3                	inc    bl
 4e4:	fe c3                	inc    bl
 4e6:	fe c3                	inc    bl
 4e8:	fe c3                	inc    bl
 4ea:	fe c3                	inc    bl
 4ec:	fe c3                	inc    bl
 4ee:	fe c3                	inc    bl
 4f0:	fe c3                	inc    bl
 4f2:	fe c3                	inc    bl
 4f4:	fe c3                	inc    bl
 4f6:	fe c3                	inc    bl
 4f8:	fe c3                	inc    bl
 4fa:	fe c3                	inc    bl
 4fc:	fe c3                	inc    bl
 4fe:	fe c3                	inc    bl
 500:	fe c3                	inc    bl
 502:	fe c3                	inc    bl
 504:	fe c3                	inc    bl
 506:	fe c3                	inc    bl
 508:	fe c3                	inc    bl
 50a:	fe c3                	inc    bl
 50c:	fe c3                	inc    bl
 50e:	fe c3                	inc    bl
 510:	fe c3                	inc    bl
 512:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 515:	fe c3                	inc    bl
 517:	fe c3                	inc    bl
 519:	fe c3                	inc    bl
 51b:	fe c3                	inc    bl
 51d:	fe c3                	inc    bl
 51f:	fe c3                	inc    bl
 521:	fe c3                	inc    bl
 523:	fe c3                	inc    bl
 525:	fe c3                	inc    bl
 527:	fe c3                	inc    bl
 529:	fe c3                	inc    bl
 52b:	fe c3                	inc    bl
 52d:	fe c3                	inc    bl
 52f:	fe c3                	inc    bl
 531:	fe c3                	inc    bl
 533:	fe c3                	inc    bl
 535:	fe c3                	inc    bl
 537:	fe c3                	inc    bl
 539:	fe c3                	inc    bl
 53b:	fe c3                	inc    bl
 53d:	fe c3                	inc    bl
 53f:	fe c3                	inc    bl
 541:	fe c3                	inc    bl
 543:	fe c3                	inc    bl
 545:	fe c3                	inc    bl
 547:	fe c3                	inc    bl
 549:	fe c3                	inc    bl
 54b:	fe c3                	inc    bl
 54d:	fe c3                	inc    bl
 54f:	fe c3                	inc    bl
 551:	fe c3                	inc    bl
 553:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 556:	fe c3                	inc    bl
 558:	fe c3                	inc    bl
 55a:	fe c3                	inc    bl
 55c:	fe c3                	inc    bl
 55e:	fe c3                	inc    bl
 560:	fe c3                	inc    bl
 562:	fe c3                	inc    bl
 564:	fe c3                	inc    bl
 566:	fe c3                	inc    bl
 568:	fe c3                	inc    bl
 56a:	fe c3                	inc    bl
 56c:	fe c3                	inc    bl
 56e:	fe c3                	inc    bl
 570:	fe c3                	inc    bl
 572:	fe c3                	inc    bl
 574:	fe c3                	inc    bl
 576:	fe c3                	inc    bl
 578:	fe c3                	inc    bl
 57a:	fe c3                	inc    bl
 57c:	fe c3                	inc    bl
 57e:	fe c3                	inc    bl
 580:	fe c3                	inc    bl
 582:	fe c3                	inc    bl
 584:	fe c3                	inc    bl
 586:	fe c3                	inc    bl
 588:	fe c3                	inc    bl
 58a:	fe c3                	inc    bl
 58c:	fe c3                	inc    bl
 58e:	fe c3                	inc    bl
 590:	fe c3                	inc    bl
 592:	fe c3                	inc    bl
 594:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 597:	fe c3                	inc    bl
 599:	fe c3                	inc    bl
 59b:	fe c3                	inc    bl
 59d:	fe c3                	inc    bl
 59f:	fe c3                	inc    bl
 5a1:	fe c3                	inc    bl
 5a3:	fe c3                	inc    bl
 5a5:	fe c3                	inc    bl
 5a7:	fe c3                	inc    bl
 5a9:	fe c3                	inc    bl
 5ab:	fe c3                	inc    bl
 5ad:	fe c3                	inc    bl
 5af:	fe c3                	inc    bl
 5b1:	fe c3                	inc    bl
 5b3:	fe c3                	inc    bl
 5b5:	fe c3                	inc    bl
 5b7:	fe c3                	inc    bl
 5b9:	fe c3                	inc    bl
 5bb:	fe c3                	inc    bl
 5bd:	fe c3                	inc    bl
 5bf:	fe c3                	inc    bl
 5c1:	fe c3                	inc    bl
 5c3:	fe c3                	inc    bl
 5c5:	fe c3                	inc    bl
 5c7:	fe c3                	inc    bl
 5c9:	fe c3                	inc    bl
 5cb:	fe c3                	inc    bl
 5cd:	fe c3                	inc    bl
 5cf:	fe c3                	inc    bl
 5d1:	fe c3                	inc    bl
 5d3:	fe c3                	inc    bl
 5d5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 5d8:	fe c3                	inc    bl
 5da:	fe c3                	inc    bl
 5dc:	fe c3                	inc    bl
 5de:	fe c3                	inc    bl
 5e0:	fe c3                	inc    bl
 5e2:	fe c3                	inc    bl
 5e4:	fe c3                	inc    bl
 5e6:	fe c3                	inc    bl
 5e8:	fe c3                	inc    bl
 5ea:	fe c3                	inc    bl
 5ec:	fe c3                	inc    bl
 5ee:	fe c3                	inc    bl
 5f0:	fe c3                	inc    bl
 5f2:	fe c3                	inc    bl
 5f4:	fe c3                	inc    bl
 5f6:	fe c3                	inc    bl
 5f8:	fe c3                	inc    bl
 5fa:	fe c3                	inc    bl
 5fc:	fe c3                	inc    bl
 5fe:	fe c3                	inc    bl
 600:	fe c3                	inc    bl
 602:	fe c3                	inc    bl
 604:	fe c3                	inc    bl
 606:	fe c3                	inc    bl
 608:	fe c3                	inc    bl
 60a:	fe c3                	inc    bl
 60c:	fe c3                	inc    bl
 60e:	fe c3                	inc    bl
 610:	fe c3                	inc    bl
 612:	fe c3                	inc    bl
 614:	fe c3                	inc    bl
 616:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 619:	fe c3                	inc    bl
 61b:	fe c3                	inc    bl
 61d:	fe c3                	inc    bl
 61f:	fe c3                	inc    bl
 621:	fe c3                	inc    bl
 623:	fe c3                	inc    bl
 625:	fe c3                	inc    bl
 627:	fe c3                	inc    bl
 629:	fe c3                	inc    bl
 62b:	fe c3                	inc    bl
 62d:	fe c3                	inc    bl
 62f:	fe c3                	inc    bl
 631:	fe c3                	inc    bl
 633:	fe c3                	inc    bl
 635:	fe c3                	inc    bl
 637:	fe c3                	inc    bl
 639:	fe c3                	inc    bl
 63b:	fe c3                	inc    bl
 63d:	fe c3                	inc    bl
 63f:	fe c3                	inc    bl
 641:	fe c3                	inc    bl
 643:	fe c3                	inc    bl
 645:	fe c3                	inc    bl
 647:	fe c3                	inc    bl
 649:	fe c3                	inc    bl
 64b:	fe c3                	inc    bl
 64d:	fe c3                	inc    bl
 64f:	fe c3                	inc    bl
 651:	fe c3                	inc    bl
 653:	fe c3                	inc    bl
 655:	fe c3                	inc    bl
 657:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 65a:	fe c3                	inc    bl
 65c:	fe c3                	inc    bl
 65e:	fe c3                	inc    bl
 660:	fe c3                	inc    bl
 662:	fe c3                	inc    bl
 664:	fe c3                	inc    bl
 666:	fe c3                	inc    bl
 668:	fe c3                	inc    bl
 66a:	fe c3                	inc    bl
 66c:	fe c3                	inc    bl
 66e:	fe c3                	inc    bl
 670:	fe c3                	inc    bl
 672:	fe c3                	inc    bl
 674:	fe c3                	inc    bl
 676:	fe c3                	inc    bl
 678:	fe c3                	inc    bl
 67a:	fe c3                	inc    bl
 67c:	fe c3                	inc    bl
 67e:	fe c3                	inc    bl
 680:	fe c3                	inc    bl
 682:	fe c3                	inc    bl
 684:	fe c3                	inc    bl
 686:	fe c3                	inc    bl
 688:	fe c3                	inc    bl
 68a:	fe c3                	inc    bl
 68c:	fe c3                	inc    bl
 68e:	fe c3                	inc    bl
 690:	fe c3                	inc    bl
 692:	fe c3                	inc    bl
 694:	fe c3                	inc    bl
 696:	fe c3                	inc    bl
 698:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 69b:	fe c3                	inc    bl
 69d:	fe c3                	inc    bl
 69f:	fe c3                	inc    bl
 6a1:	fe c3                	inc    bl
 6a3:	fe c3                	inc    bl
 6a5:	fe c3                	inc    bl
 6a7:	fe c3                	inc    bl
 6a9:	fe c3                	inc    bl
 6ab:	fe c3                	inc    bl
 6ad:	fe c3                	inc    bl
 6af:	fe c3                	inc    bl
 6b1:	fe c3                	inc    bl
 6b3:	fe c3                	inc    bl
 6b5:	fe c3                	inc    bl
 6b7:	fe c3                	inc    bl
 6b9:	fe c3                	inc    bl
 6bb:	fe c3                	inc    bl
 6bd:	fe c3                	inc    bl
 6bf:	fe c3                	inc    bl
 6c1:	fe c3                	inc    bl
 6c3:	fe c3                	inc    bl
 6c5:	fe c3                	inc    bl
 6c7:	fe c3                	inc    bl
 6c9:	fe c3                	inc    bl
 6cb:	fe c3                	inc    bl
 6cd:	fe c3                	inc    bl
 6cf:	fe c3                	inc    bl
 6d1:	fe c3                	inc    bl
 6d3:	fe c3                	inc    bl
 6d5:	fe c3                	inc    bl
 6d7:	fe c3                	inc    bl
 6d9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 6dc:	fe c3                	inc    bl
 6de:	fe c3                	inc    bl
 6e0:	fe c3                	inc    bl
 6e2:	fe c3                	inc    bl
 6e4:	fe c3                	inc    bl
 6e6:	fe c3                	inc    bl
 6e8:	fe c3                	inc    bl
 6ea:	fe c3                	inc    bl
 6ec:	fe c3                	inc    bl
 6ee:	fe c3                	inc    bl
 6f0:	fe c3                	inc    bl
 6f2:	fe c3                	inc    bl
 6f4:	fe c3                	inc    bl
 6f6:	fe c3                	inc    bl
 6f8:	fe c3                	inc    bl
 6fa:	fe c3                	inc    bl
 6fc:	fe c3                	inc    bl
 6fe:	fe c3                	inc    bl
 700:	fe c3                	inc    bl
 702:	fe c3                	inc    bl
 704:	fe c3                	inc    bl
 706:	fe c3                	inc    bl
 708:	fe c3                	inc    bl
 70a:	fe c3                	inc    bl
 70c:	fe c3                	inc    bl
 70e:	fe c3                	inc    bl
 710:	fe c3                	inc    bl
 712:	fe c3                	inc    bl
 714:	fe c3                	inc    bl
 716:	fe c3                	inc    bl
 718:	fe c3                	inc    bl
 71a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 71d:	fe c3                	inc    bl
 71f:	fe c3                	inc    bl
 721:	fe c3                	inc    bl
 723:	fe c3                	inc    bl
 725:	fe c3                	inc    bl
 727:	fe c3                	inc    bl
 729:	fe c3                	inc    bl
 72b:	fe c3                	inc    bl
 72d:	fe c3                	inc    bl
 72f:	fe c3                	inc    bl
 731:	fe c3                	inc    bl
 733:	fe c3                	inc    bl
 735:	fe c3                	inc    bl
 737:	fe c3                	inc    bl
 739:	fe c3                	inc    bl
 73b:	fe c3                	inc    bl
 73d:	fe c3                	inc    bl
 73f:	fe c3                	inc    bl
 741:	fe c3                	inc    bl
 743:	fe c3                	inc    bl
 745:	fe c3                	inc    bl
 747:	fe c3                	inc    bl
 749:	fe c3                	inc    bl
 74b:	fe c3                	inc    bl
 74d:	fe c3                	inc    bl
 74f:	fe c3                	inc    bl
 751:	fe c3                	inc    bl
 753:	fe c3                	inc    bl
 755:	fe c3                	inc    bl
 757:	fe c3                	inc    bl
 759:	fe c3                	inc    bl
 75b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 75e:	fe c3                	inc    bl
 760:	fe c3                	inc    bl
 762:	fe c3                	inc    bl
 764:	fe c3                	inc    bl
 766:	fe c3                	inc    bl
 768:	fe c3                	inc    bl
 76a:	fe c3                	inc    bl
 76c:	fe c3                	inc    bl
 76e:	fe c3                	inc    bl
 770:	fe c3                	inc    bl
 772:	fe c3                	inc    bl
 774:	fe c3                	inc    bl
 776:	fe c3                	inc    bl
 778:	fe c3                	inc    bl
 77a:	fe c3                	inc    bl
 77c:	fe c3                	inc    bl
 77e:	fe c3                	inc    bl
 780:	fe c3                	inc    bl
 782:	fe c3                	inc    bl
 784:	fe c3                	inc    bl
 786:	fe c3                	inc    bl
 788:	fe c3                	inc    bl
 78a:	fe c3                	inc    bl
 78c:	fe c3                	inc    bl
 78e:	fe c3                	inc    bl
 790:	fe c3                	inc    bl
 792:	fe c3                	inc    bl
 794:	fe c3                	inc    bl
 796:	fe c3                	inc    bl
 798:	fe c3                	inc    bl
 79a:	fe c3                	inc    bl
 79c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 79f:	fe c3                	inc    bl
 7a1:	fe c3                	inc    bl
 7a3:	fe c3                	inc    bl
 7a5:	fe c3                	inc    bl
 7a7:	fe c3                	inc    bl
 7a9:	fe c3                	inc    bl
 7ab:	fe c3                	inc    bl
 7ad:	fe c3                	inc    bl
 7af:	fe c3                	inc    bl
 7b1:	fe c3                	inc    bl
 7b3:	fe c3                	inc    bl
 7b5:	fe c3                	inc    bl
 7b7:	fe c3                	inc    bl
 7b9:	fe c3                	inc    bl
 7bb:	fe c3                	inc    bl
 7bd:	fe c3                	inc    bl
 7bf:	fe c3                	inc    bl
 7c1:	fe c3                	inc    bl
 7c3:	fe c3                	inc    bl
 7c5:	fe c3                	inc    bl
 7c7:	fe c3                	inc    bl
 7c9:	fe c3                	inc    bl
 7cb:	fe c3                	inc    bl
 7cd:	fe c3                	inc    bl
 7cf:	fe c3                	inc    bl
 7d1:	fe c3                	inc    bl
 7d3:	fe c3                	inc    bl
 7d5:	fe c3                	inc    bl
 7d7:	fe c3                	inc    bl
 7d9:	fe c3                	inc    bl
 7db:	fe c3                	inc    bl
 7dd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 7e0:	fe c3                	inc    bl
 7e2:	fe c3                	inc    bl
 7e4:	fe c3                	inc    bl
 7e6:	fe c3                	inc    bl
 7e8:	fe c3                	inc    bl
 7ea:	fe c3                	inc    bl
 7ec:	fe c3                	inc    bl
 7ee:	fe c3                	inc    bl
 7f0:	fe c3                	inc    bl
 7f2:	fe c3                	inc    bl
 7f4:	fe c3                	inc    bl
 7f6:	fe c3                	inc    bl
 7f8:	fe c3                	inc    bl
 7fa:	fe c3                	inc    bl
 7fc:	fe c3                	inc    bl
 7fe:	fe c3                	inc    bl
 800:	fe c3                	inc    bl
 802:	fe c3                	inc    bl
 804:	fe c3                	inc    bl
 806:	fe c3                	inc    bl
 808:	fe c3                	inc    bl
 80a:	fe c3                	inc    bl
 80c:	fe c3                	inc    bl
 80e:	fe c3                	inc    bl
 810:	fe c3                	inc    bl
 812:	fe c3                	inc    bl
 814:	fe c3                	inc    bl
 816:	fe c3                	inc    bl
 818:	fe c3                	inc    bl
 81a:	fe c3                	inc    bl
 81c:	fe c3                	inc    bl
 81e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 821:	fe c3                	inc    bl
 823:	fe c3                	inc    bl
 825:	fe c3                	inc    bl
 827:	fe c3                	inc    bl
 829:	fe c3                	inc    bl
 82b:	fe c3                	inc    bl
 82d:	fe c3                	inc    bl
 82f:	fe c3                	inc    bl
 831:	fe c3                	inc    bl
 833:	fe c3                	inc    bl
 835:	fe c3                	inc    bl
 837:	fe c3                	inc    bl
 839:	fe c3                	inc    bl
 83b:	fe c3                	inc    bl
 83d:	fe c3                	inc    bl
 83f:	fe c3                	inc    bl
 841:	fe c3                	inc    bl
 843:	fe c3                	inc    bl
 845:	fe c3                	inc    bl
 847:	fe c3                	inc    bl
 849:	fe c3                	inc    bl
 84b:	fe c3                	inc    bl
 84d:	fe c3                	inc    bl
 84f:	fe c3                	inc    bl
 851:	fe c3                	inc    bl
 853:	fe c3                	inc    bl
 855:	fe c3                	inc    bl
 857:	fe c3                	inc    bl
 859:	fe c3                	inc    bl
 85b:	fe c3                	inc    bl
 85d:	fe c3                	inc    bl
 85f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 862:	fe c3                	inc    bl
 864:	fe c3                	inc    bl
 866:	fe c3                	inc    bl
 868:	fe c3                	inc    bl
 86a:	fe c3                	inc    bl
 86c:	fe c3                	inc    bl
 86e:	fe c3                	inc    bl
 870:	fe c3                	inc    bl
 872:	fe c3                	inc    bl
 874:	fe c3                	inc    bl
 876:	fe c3                	inc    bl
 878:	fe c3                	inc    bl
 87a:	fe c3                	inc    bl
 87c:	fe c3                	inc    bl
 87e:	fe c3                	inc    bl
 880:	fe c3                	inc    bl
 882:	fe c3                	inc    bl
 884:	fe c3                	inc    bl
 886:	fe c3                	inc    bl
 888:	fe c3                	inc    bl
 88a:	fe c3                	inc    bl
 88c:	fe c3                	inc    bl
 88e:	fe c3                	inc    bl
 890:	fe c3                	inc    bl
 892:	fe c3                	inc    bl
 894:	fe c3                	inc    bl
 896:	fe c3                	inc    bl
 898:	fe c3                	inc    bl
 89a:	fe c3                	inc    bl
 89c:	fe c3                	inc    bl
 89e:	fe c3                	inc    bl
 8a0:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 8a3:	fe c3                	inc    bl
 8a5:	fe c3                	inc    bl
 8a7:	fe c3                	inc    bl
 8a9:	fe c3                	inc    bl
 8ab:	fe c3                	inc    bl
 8ad:	fe c3                	inc    bl
 8af:	fe c3                	inc    bl
 8b1:	fe c3                	inc    bl
 8b3:	fe c3                	inc    bl
 8b5:	fe c3                	inc    bl
 8b7:	fe c3                	inc    bl
 8b9:	fe c3                	inc    bl
 8bb:	fe c3                	inc    bl
 8bd:	fe c3                	inc    bl
 8bf:	fe c3                	inc    bl
 8c1:	fe c3                	inc    bl
 8c3:	fe c3                	inc    bl
 8c5:	fe c3                	inc    bl
 8c7:	fe c3                	inc    bl
 8c9:	fe c3                	inc    bl
 8cb:	fe c3                	inc    bl
 8cd:	fe c3                	inc    bl
 8cf:	fe c3                	inc    bl
 8d1:	fe c3                	inc    bl
 8d3:	fe c3                	inc    bl
 8d5:	fe c3                	inc    bl
 8d7:	fe c3                	inc    bl
 8d9:	fe c3                	inc    bl
 8db:	fe c3                	inc    bl
 8dd:	fe c3                	inc    bl
 8df:	fe c3                	inc    bl
 8e1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 8e4:	fe c3                	inc    bl
 8e6:	fe c3                	inc    bl
 8e8:	fe c3                	inc    bl
 8ea:	fe c3                	inc    bl
 8ec:	fe c3                	inc    bl
 8ee:	fe c3                	inc    bl
 8f0:	fe c3                	inc    bl
 8f2:	fe c3                	inc    bl
 8f4:	fe c3                	inc    bl
 8f6:	fe c3                	inc    bl
 8f8:	fe c3                	inc    bl
 8fa:	fe c3                	inc    bl
 8fc:	fe c3                	inc    bl
 8fe:	fe c3                	inc    bl
 900:	fe c3                	inc    bl
 902:	fe c3                	inc    bl
 904:	fe c3                	inc    bl
 906:	fe c3                	inc    bl
 908:	fe c3                	inc    bl
 90a:	fe c3                	inc    bl
 90c:	fe c3                	inc    bl
 90e:	fe c3                	inc    bl
 910:	fe c3                	inc    bl
 912:	fe c3                	inc    bl
 914:	fe c3                	inc    bl
 916:	fe c3                	inc    bl
 918:	fe c3                	inc    bl
 91a:	fe c3                	inc    bl
 91c:	fe c3                	inc    bl
 91e:	fe c3                	inc    bl
 920:	fe c3                	inc    bl
 922:	83 e8 01             	sub    eax,0x1
 925:	0f 85 55 f7 ff ff    	jne    0x80
 92b:	66 90                	xchg   ax,ax
 92d:	66 90                	xchg   ax,ax
 92f:	66 90                	xchg   ax,ax
 931:	66 90                	xchg   ax,ax
 933:	66 90                	xchg   ax,ax
 935:	66 90                	xchg   ax,ax
 937:	66 90                	xchg   ax,ax
 939:	66 90                	xchg   ax,ax
 93b:	48 81 c4 a4 6a 00 00 	add    rsp,0x6aa4
 942:	41 59                	pop    r9
 944:	41 58                	pop    r8
 946:	5f                   	pop    rdi
 947:	5e                   	pop    rsi
 948:	5d                   	pop    rbp
 949:	5b                   	pop    rbx
 94a:	0f 77                	emms   
 94c:	c3                   	ret    
